/* pinyinTable.js — 汉字→拼音数据表（T514 拼音首字母搜索兼容层数据源）。
 * 生成：pypinyin 0.55.0，数据源 mozillazg/pinyin-data（MIT）。
 * 覆盖：GB2312 全部 6763 汉字 + 项目文本增补 4 字；多音字 1816 个（每字至多 2 读音，ü→v）。
 * 平行数组：PINYIN_CHARS[i] ↔ PINYIN_READ 第 i 段（读音逗号分隔多音，空格分隔字）。
 * 只读数据，检索时惰性建 Map，零外发。勿手改，重跑生成脚本再生成。
 */
export const PINYIN_CHARS =
  "啊阿埃挨哎唉哀皑癌蔼矮艾碍爱隘鞍氨安俺按暗岸胺案肮昂盎凹敖熬翱袄傲奥懊澳芭捌扒叭吧笆八疤巴拔跋靶把耙坝霸罢爸白柏百摆佰败拜稗斑班搬扳般颁板版扮拌伴瓣半办绊邦帮梆榜膀绑棒磅蚌镑傍谤苞胞包褒剥薄雹保堡饱宝抱报暴豹鲍爆杯碑悲卑北辈背贝钡倍狈备惫焙"
  + "被奔苯本笨崩绷甭泵蹦迸逼鼻比鄙笔彼碧蓖蔽毕毙毖币庇痹闭敝弊必辟壁臂避陛鞭边编贬扁便变卞辨辩辫遍标彪膘表鳖憋别瘪彬斌濒滨宾摈兵冰柄丙秉饼炳病并玻菠播拨钵波博勃搏铂箔伯帛舶脖膊渤泊驳捕卜哺补埠不布步簿部怖擦猜裁材才财睬踩采彩菜蔡餐参蚕残惭惨灿苍"
  + "舱仓沧藏操糙槽曹草厕策侧册测层蹭插叉茬茶查碴搽察岔差诧拆柴豺搀掺蝉馋谗缠铲产阐颤昌猖场尝常长偿肠厂敞畅唱倡超抄钞朝嘲潮巢吵炒车扯撤掣彻澈郴臣辰尘晨忱沉陈趁衬撑称城橙成呈乘程惩澄诚承逞骋秤吃痴持匙池迟弛驰耻齿侈尺赤翅斥炽充冲虫崇宠抽酬畴踌稠愁"
  + "筹仇绸瞅丑臭初出橱厨躇锄雏滁除楚础储矗搐触处揣川穿椽传船喘串疮窗幢床闯创吹炊捶锤垂春椿醇唇淳纯蠢戳绰疵茨磁雌辞慈瓷词此刺赐次聪葱囱匆从丛凑粗醋簇促蹿篡窜摧崔催脆瘁粹淬翠村存寸磋撮搓措挫错搭达答瘩打大呆歹傣戴带殆代贷袋待逮怠耽担丹单郸掸胆旦氮"
  + "但惮淡诞弹蛋当挡党荡档刀捣蹈倒岛祷导到稻悼道盗德得的蹬灯登等瞪凳邓堤低滴迪敌笛狄涤翟嫡抵底地蒂第帝弟递缔颠掂滇碘点典靛垫电佃甸店惦奠淀殿碉叼雕凋刁掉吊钓调跌爹碟蝶迭谍叠丁盯叮钉顶鼎锭定订丢东冬董懂动栋侗恫冻洞兜抖斗陡豆逗痘都督毒犊独读堵睹赌"
  + "杜镀肚度渡妒端短锻段断缎堆兑队对墩吨蹲敦顿囤钝盾遁掇哆多夺垛躲朵跺舵剁惰堕蛾峨鹅俄额讹娥恶厄扼遏鄂饿恩而儿耳尔饵洱二贰发罚筏伐乏阀法珐藩帆番翻樊矾钒繁凡烦反返范贩犯饭泛坊芳方肪房防妨仿访纺放菲非啡飞肥匪诽吠肺废沸费芬酚吩氛分纷坟焚汾粉奋份忿"
  + "愤粪丰封枫蜂峰锋风疯烽逢冯缝讽奉凤佛否夫敷肤孵扶拂辐幅氟符伏俘服浮涪福袱弗甫抚辅俯釜斧脯腑府腐赴副覆赋复傅付阜父腹负富讣附妇缚咐噶嘎该改概钙盖溉干甘杆柑竿肝赶感秆敢赣冈刚钢缸肛纲岗港杠篙皋高膏羔糕搞镐稿告哥歌搁戈鸽胳疙割革葛格蛤阁隔铬个各给"
  + "根跟耕更庚羹埂耿梗工攻功恭龚供躬公宫弓巩汞拱贡共钩勾沟苟狗垢构购够辜菇咕箍估沽孤姑鼓古蛊骨谷股故顾固雇刮瓜剐寡挂褂乖拐怪棺关官冠观管馆罐惯灌贯光广逛瑰规圭硅归龟闺轨鬼诡癸桂柜跪贵刽辊滚棍锅郭国果裹过哈骸孩海氦亥害骇酣憨邯韩含涵寒函喊罕翰撼捍"
  + "旱憾悍焊汗汉夯杭航壕嚎豪毫郝好耗号浩呵喝荷菏核禾和何合盒貉阂河涸赫褐鹤贺嘿黑痕很狠恨哼亨横衡恒轰哄烘虹鸿洪宏弘红喉侯猴吼厚候后呼乎忽瑚壶葫胡蝴狐糊湖弧虎唬护互沪户花哗华猾滑画划化话槐徊怀淮坏欢环桓还缓换患唤痪豢焕涣宦幻荒慌黄磺蝗簧皇凰惶煌晃"
  + "幌恍谎灰挥辉徽恢蛔回毁悔慧卉惠晦贿秽会烩汇讳诲绘荤昏婚魂浑混豁活伙火获或惑霍货祸击圾基机畸稽积箕肌饥迹激讥鸡姬绩缉吉极棘辑籍集及急疾汲即嫉级挤几脊己蓟技冀季伎祭剂悸济寄寂计记既忌际妓继纪嘉枷夹佳家加荚颊贾甲钾假稼价架驾嫁歼监坚尖笺间煎兼肩艰"
  + "奸缄茧检柬碱硷拣捡简俭剪减荐槛鉴践贱见键箭件健舰剑饯渐溅涧建僵姜将浆江疆蒋桨奖讲匠酱降蕉椒礁焦胶交郊浇骄娇嚼搅铰矫侥脚狡角饺缴绞剿教酵轿较叫窖揭接皆秸街阶截劫节桔杰捷睫竭洁结解姐戒藉芥界借介疥诫届巾筋斤金今津襟紧锦仅谨进靳晋禁近烬浸尽劲荆兢"
  + "茎睛晶鲸京惊精粳经井警景颈静境敬镜径痉靖竟竞净炯窘揪究纠玖韭久灸九酒厩救旧臼舅咎就疚鞠拘狙疽居驹菊局咀矩举沮聚拒据巨具距踞锯俱句惧炬剧捐鹃娟倦眷卷绢撅攫抉掘倔爵觉决诀绝均菌钧军君峻俊竣浚郡骏喀咖卡咯开揩楷凯慨刊堪勘坎砍看康慷糠扛抗亢炕考拷烤"
  + "靠坷苛柯棵磕颗科壳咳可渴克刻客课肯啃垦恳坑吭空恐孔控抠口扣寇枯哭窟苦酷库裤夸垮挎跨胯块筷侩快宽款匡筐狂框矿眶旷况亏盔岿窥葵奎魁傀馈愧溃坤昆捆困括扩廓阔垃拉喇蜡腊辣啦莱来赖蓝婪栏拦篮阑兰澜谰揽览懒缆烂滥琅榔狼廊郎朗浪捞劳牢老佬姥酪烙涝勒乐雷镭"
  + "蕾磊累儡垒擂肋类泪棱楞冷厘梨犁黎篱狸离漓理李里鲤礼莉荔吏栗丽厉励砾历利傈例俐痢立粒沥隶力璃哩俩联莲连镰廉怜涟帘敛脸链恋炼练粮凉梁粱良两辆量晾亮谅撩聊僚疗燎寥辽潦了撂镣廖料列裂烈劣猎琳林磷霖临邻鳞淋凛赁吝拎玲菱零龄铃伶羚凌灵陵岭领另令溜琉榴硫"
  + "馏留刘瘤流柳六龙聋咙笼窿隆垄拢陇楼娄搂篓漏陋芦卢颅庐炉掳卤虏鲁麓碌露路赂鹿潞禄录陆戮驴吕铝侣旅履屡缕虑氯律率滤绿峦挛孪滦卵乱掠略抡轮伦仑沦纶论萝螺罗逻锣箩骡裸落洛骆络妈麻玛码蚂马骂嘛吗埋买麦卖迈脉瞒馒蛮满蔓曼慢漫谩芒茫盲氓忙莽猫茅锚毛矛铆卯"
  + "茂冒帽貌贸么玫枚梅酶霉煤没眉媒镁每美昧寐妹媚门闷们萌蒙檬盟锰猛梦孟眯醚靡糜迷谜弥米秘觅泌蜜密幂棉眠绵冕免勉娩缅面苗描瞄藐秒渺庙妙蔑灭民抿皿敏悯闽明螟鸣铭名命谬摸摹蘑模膜磨摩魔抹末莫墨默沫漠寞陌谋牟某拇牡亩姆母墓暮幕募慕木目睦牧穆拿哪呐钠那娜"
  + "纳氖乃奶耐奈南男难囊挠脑恼闹淖呢馁内嫩能妮霓倪泥尼拟你匿腻逆溺蔫拈年碾撵捻念娘酿鸟尿捏聂孽啮镊镍涅您柠狞凝宁拧泞牛扭钮纽脓浓农弄奴努怒女暖虐疟挪懦糯诺哦欧鸥殴藕呕偶沤啪趴爬帕怕琶拍排牌徘湃派攀潘盘磐盼畔判叛乓庞旁耪胖抛咆刨炮袍跑泡呸胚培裴赔"
  + "陪配佩沛喷盆砰抨烹澎彭蓬棚硼篷膨朋鹏捧碰坯砒霹批披劈琵毗啤脾疲皮匹痞僻屁譬篇偏片骗飘漂瓢票撇瞥拼频贫品聘乒坪苹萍平凭瓶评屏坡泼颇婆破魄迫粕剖扑铺仆莆葡菩蒲埔朴圃普浦谱曝瀑期欺栖戚妻七凄漆柒沏其棋奇歧畦崎脐齐旗祈祁骑起岂乞企启契砌器气迄弃汽泣"
  + "讫掐恰洽牵扦钎铅千迁签仟谦乾黔钱钳前潜遣浅谴堑嵌欠歉枪呛腔羌墙蔷强抢橇锹敲悄桥瞧乔侨巧鞘撬翘峭俏窍切茄且怯窃钦侵亲秦琴勤芹擒禽寝沁青轻氢倾卿清擎晴氰情顷请庆琼穷秋丘邱球求囚酋泅趋区蛆曲躯屈驱渠取娶龋趣去圈颧权醛泉全痊拳犬券劝缺炔瘸却鹊榷确雀"
  + "裙群然燃冉染瓤壤攘嚷让饶扰绕惹热壬仁人忍韧任认刃妊纫扔仍日戎茸蓉荣融熔溶容绒冗揉柔肉茹蠕儒孺如辱乳汝入褥软阮蕊瑞锐闰润若弱撒洒萨腮鳃塞赛三叁伞散桑嗓丧搔骚扫嫂瑟色涩森僧莎砂杀刹沙纱傻啥煞筛晒珊苫杉山删煽衫闪陕擅赡膳善汕扇缮墒伤商赏晌上尚裳梢"
  + "捎稍烧芍勺韶少哨邵绍奢赊蛇舌舍赦摄射慑涉社设砷申呻伸身深娠绅神沈审婶甚肾慎渗声生甥牲升绳省盛剩胜圣师失狮施湿诗尸虱十石拾时什食蚀实识史矢使屎驶始式示士世柿事拭誓逝势是嗜噬适仕侍释饰氏市恃室视试收手首守寿授售受瘦兽蔬枢梳殊抒输叔舒淑疏书赎孰熟"
  + "薯暑曙署蜀黍鼠属术述树束戍竖墅庶数漱恕刷耍摔衰甩帅栓拴霜双爽谁水睡税吮瞬顺舜说硕朔烁斯撕嘶思私司丝死肆寺嗣四伺似饲巳松耸怂颂送宋讼诵搜艘擞嗽苏酥俗素速粟僳塑溯宿诉肃酸蒜算虽隋随绥髓碎岁穗遂隧祟孙损笋蓑梭唆缩琐索锁所塌他它她塔獭挞蹋踏胎苔抬台"
  + "泰酞太态汰坍摊贪瘫滩坛檀痰潭谭谈坦毯袒碳探叹炭汤塘搪堂棠膛唐糖倘躺淌趟烫掏涛滔绦萄桃逃淘陶讨套特藤腾疼誊梯剔踢锑提题蹄啼体替嚏惕涕剃屉天添填田甜恬舔腆挑条迢眺跳贴铁帖厅听烃汀廷停亭庭挺艇通桐酮瞳同铜彤童桶捅筒统痛偷投头透凸秃突图徒途涂屠土吐"
  + "兔湍团推颓腿蜕褪退吞屯臀拖托脱鸵陀驮驼椭妥拓唾挖哇蛙洼娃瓦袜歪外豌弯湾玩顽丸烷完碗挽晚皖惋宛婉万腕汪王亡枉网往旺望忘妄威巍微危韦违桅围唯惟为潍维苇萎委伟伪尾纬未蔚味畏胃喂魏位渭谓尉慰卫瘟温蚊文闻纹吻稳紊问嗡翁瓮挝蜗涡窝我斡卧握沃巫呜钨乌污诬"
  + "屋无芜梧吾吴毋武五捂午舞伍侮坞戊雾晤物勿务悟误昔熙析西硒矽晰嘻吸锡牺稀息希悉膝夕惜熄烯溪汐犀檄袭席习媳喜铣洗系隙戏细瞎虾匣霞辖暇峡侠狭下厦夏吓掀锨先仙鲜纤咸贤衔舷闲涎弦嫌显险现献县腺馅羡宪陷限线相厢镶香箱襄湘乡翔祥详想响享项巷橡像向象萧硝霄"
  + "削哮嚣销消宵淆晓小孝校肖啸笑效楔些歇蝎鞋协挟携邪斜胁谐写械卸蟹懈泄泻谢屑薪芯锌欣辛新忻心信衅星腥猩惺兴刑型形邢行醒幸杏性姓兄凶胸匈汹雄熊休修羞朽嗅锈秀袖绣墟戌需虚嘘须徐许蓄酗叙旭序畜恤絮婿绪续轩喧宣悬旋玄选癣眩绚靴薛学穴雪血勋熏循旬询寻驯巡"
  + "殉汛训讯逊迅压押鸦鸭呀丫芽牙蚜崖衙涯雅哑亚讶焉咽阉烟淹盐严研蜒岩延言颜阎炎沿奄掩眼衍演艳堰燕厌砚雁唁彦焰宴谚验殃央鸯秧杨扬佯疡羊洋阳氧仰痒养样漾邀腰妖瑶摇尧遥窑谣姚咬舀药要耀椰噎耶爷野冶也页掖业叶曳腋夜液一壹医揖铱依伊衣颐夷遗移仪胰疑沂宜姨"
  + "彝椅蚁倚已乙矣以艺抑易邑屹亿役臆逸肄疫亦裔意毅忆义益溢诣议谊译异翼翌绎茵荫因殷音阴姻吟银淫寅饮尹引隐印英樱婴鹰应缨莹萤营荧蝇迎赢盈影颖硬映哟拥佣臃痈庸雍踊蛹咏泳涌永恿勇用幽优悠忧尤由邮铀犹油游酉有友右佑釉诱又幼迂淤于盂榆虞愚舆余俞逾鱼愉渝渔"
  + "隅予娱雨与屿禹宇语羽玉域芋郁吁遇喻峪御愈欲狱育誉浴寓裕预豫驭鸳渊冤元垣袁原援辕园员圆猿源缘远苑愿怨院曰约越跃钥岳粤月悦阅耘云郧匀陨允运蕴酝晕韵孕匝砸杂栽哉灾宰载再在咱攒暂赞赃脏葬遭糟凿藻枣早澡蚤躁噪造皂灶燥责择则泽贼怎增憎曾赠扎喳渣札轧铡闸"
  + "眨栅榨咋乍炸诈摘斋宅窄债寨瞻毡詹粘沾盏斩辗崭展蘸栈占战站湛绽樟章彰漳张掌涨杖丈帐账仗胀瘴障招昭找沼赵照罩兆肇召遮折哲蛰辙者锗蔗这浙珍斟真甄砧臻贞针侦枕疹诊震振镇阵蒸挣睁征狰争怔整拯正政帧症郑证芝枝支吱蜘知肢脂汁之织职直植殖执值侄址指止趾只旨"
  + "纸志挚掷至致置帜峙制智秩稚质炙痔滞治窒中盅忠钟衷终种肿重仲众舟周州洲诌粥轴肘帚咒皱宙昼骤珠株蛛朱猪诸诛逐竹烛煮拄瞩嘱主著柱助蛀贮铸筑住注祝驻抓爪拽专砖转撰赚篆桩庄装妆撞壮状椎锥追赘坠缀谆准捉拙卓桌琢茁酌啄着灼浊兹咨资姿滋淄孜紫仔籽滓子自渍字"
  + "鬃棕踪宗综总纵邹走奏揍租足卒族祖诅阻组钻纂嘴醉最罪尊遵昨左佐柞做作坐座亍丌兀丐廿卅丕亘丞鬲孬噩丨禺丿匕乇夭爻卮氐囟胤馗毓睾鼗丶亟鼐乜乩亓芈孛啬嘏仄厍厝厣厥厮靥赝匚叵匦匮匾赜卦卣刂刈刎刭刳刿剀剌剞剡剜蒯剽劂劁劐劓冂罔亻仃仉仂仨仡仫仞伛仳伢佤仵"
  + "伥伧伉伫佞佧攸佚佝佟佗伲伽佶佴侑侉侃侏佾佻侪佼侬侔俦俨俪俅俚俣俜俑俟俸倩偌俳倬倏倮倭俾倜倌倥倨偾偃偕偈偎偬偻傥傧傩傺僖儆僭僬僦僮儇儋仝氽佘佥俎龠汆籴兮巽黉馘冁夔勹匍訇匐凫夙兕亠兖亳衮袤亵脔裒禀嬴蠃羸冫冱冽冼凇冖冢冥讠讦讧讪讴讵讷诂诃诋诏诎诒"
  + "诓诔诖诘诙诜诟诠诤诨诩诮诰诳诶诹诼诿谀谂谄谇谌谏谑谒谔谕谖谙谛谘谝谟谠谡谥谧谪谫谮谯谲谳谵谶卩卺阝阢阡阱阪阽阼陂陉陔陟陧陬陲陴隈隍隗隰邗邛邝邙邬邡邴邳邶邺邸邰郏郅邾郐郄郇郓郦郢郜郗郛郫郯郾鄄鄢鄞鄣鄱鄯鄹酃酆刍奂劢劬劭劾哿勐勖勰叟燮矍廴凵凼鬯"
  + "厶弁畚巯坌垩垡塾墼壅壑圩圬圪圳圹圮圯坜圻坂坩垅坫垆坼坻坨坭坶坳垭垤垌垲埏垧垴垓垠埕埘埚埙埒垸埴埯埸埤埝堋堍埽埭堀堞堙塄堠塥塬墁墉墚墀馨鼙懿艹艽艿芏芊芨芄芎芑芗芙芫芸芾芰苈苊苣芘芷芮苋苌苁芩芴芡芪芟苄苎芤苡茉苷苤茏茇苜苴苒苘茌苻苓茑茚茆茔茕苠"
  + "苕茜荑荛荜茈莒茼茴茱莛荞茯荏荇荃荟荀茗荠茭茺茳荦荥荨茛荩荬荪荭荮莰荸莳莴莠莪莓莜莅荼莶莩荽莸荻莘莞莨莺莼菁萁菥菘堇萘萋菝菽菖萜萸萑萆菔菟萏萃菸菹菪菅菀萦菰菡葜葑葚葙葳蒇蒈葺蒉葸萼葆葩葶蒌蒎萱葭蓁蓍蓐蓦蒽蓓蓊蒿蒺蓠蒡蒹蒴蒗蓥蓣蔌甍蔸蓰蔹蔟蔺蕖"
  + "蔻蓿蓼蕙蕈蕨蕤蕞蕺瞢蕃蕲蕻薤薨薇薏蕹薮薜薅薹薷薰藓藁藜藿蘧蘅蘩蘖蘼廾弈夼奁耷奕奚奘匏尢尥尬尴扌扪抟抻拊拚拗拮挢拶挹捋捃掭揶捱捺掎掴捭掬掊捩掮掼揲揸揠揿揄揞揎摒揆掾摅摁搋搛搠搌搦搡摞撄摭撖摺撷撸撙撺擀擐擗擤擢攉攥攮弋忒甙弑卟叱叽叩叨叻吒吖吆呋"
  + "呒呓呔呖呃吡呗呙吣吲咂咔呷呱呤咚咛咄呶呦咝哐咭哂咴哒咧咦哓哔呲咣哕咻咿哌哙哚哜咩咪咤哝哏哞唛哧唠哽唔哳唢唣唏唑唧唪啧喏喵啉啭啁啕唿啐唼唷啖啵啶啷唳唰啜喋嗒喃喱喹喈喁喟啾嗖喑啻嗟喽喾喔喙嗪嗷嗉嘟嗑嗫嗬嗔嗦嗝嗄嗯嗥嗲嗳嗌嗍嗨嗵嗤辔嘞嘈嘌嘁嘤嘣嗾"
  + "嘀嘧嘭噘嘹噗嘬噍噢噙噜噌噔嚆噤噱噫噻噼嚅嚓嚯囔囗囝囡囵囫囹囿圄圊圉圜帏帙帔帑帱帻帼帷幄幔幛幞幡岌屺岍岐岖岈岘岙岑岚岜岵岢岽岬岫岱岣峁岷峄峒峤峋峥崂崃崧崦崮崤崞崆崛嵘崾崴崽嵬嵛嵯嵝嵫嵋嵊嵩嵴嶂嶙嶝豳嶷巅彳彷徂徇徉後徕徙徜徨徭徵徼衢彡犭犰犴犷犸"
  + "狃狁狎狍狒狨狯狩狲狴狷猁狳猃狺狻猗猓猡猊猞猝猕猢猹猥猬猸猱獐獍獗獠獬獯獾舛夥飧夤夂饣饧饨饩饪饫饬饴饷饽馀馄馇馊馍馐馑馓馔馕庀庑庋庖庥庠庹庵庾庳赓廒廑廛廨廪膺忄忉忖忏怃忮怄忡忤忾怅怆忪忭忸怙怵怦怛怏怍怩怫怊怿怡恸恹恻恺恂恪恽悖悚悭悝悃悒悌悛惬"
  + "悻悱惝惘惆惚悴愠愦愕愣惴愀愎愫慊慵憬憔憧憷懔懵忝隳闩闫闱闳闵闶闼闾阃阄阆阈阊阋阌阍阏阒阕阖阗阙阚丬爿戕氵汔汜汊沣沅沐沔沌汨汩汴汶沆沩泐泔沭泷泸泱泗沲泠泖泺泫泮沱泓泯泾洹洧洌浃浈洇洄洙洎洫浍洮洵洚浏浒浔洳涑浯涞涠浞涓涔浜浠浼浣渚淇淅淞渎涿淠渑"
  + "淦淝淙渖涫渌涮渫湮湎湫溲湟溆湓湔渲渥湄滟溱溘滠漭滢溥溧溽溻溷滗溴滏溏滂溟潢潆潇漤漕滹漯漶潋潴漪漉漩澉澍澌潸潲潼潺濑濉澧澹澶濂濡濮濞濠濯瀚瀣瀛瀹瀵灏灞宀宄宕宓宥宸甯骞搴寤寮褰寰蹇謇辶迓迕迥迮迤迩迦迳迨逅逄逋逦逑逍逖逡逵逶逭逯遄遑遒遐遨遘遢遛暹"
  + "遴遽邂邈邃邋彐彗彖彘尻咫屐屙孱屣屦羼弪弩弭艴弼鬻屮妁妃妍妩妪妣妗姊妫妞妤姒妲妯姗妾娅娆姝娈姣姘姹娌娉娲娴娑娣娓婀婧婊婕娼婢婵胬媪媛婷婺媾嫫媲嫒嫔媸嫠嫣嫱嫖嫦嫘嫜嬉嬗嬖嬲嬷孀尕尜孚孥孳孑孓孢驵驷驸驺驿驽骀骁骅骈骊骐骒骓骖骘骛骜骝骟骠骢骣骥骧纟"
  + "纡纣纥纨纩纭纰纾绀绁绂绉绋绌绐绔绗绛绠绡绨绫绮绯绱绲缍绶绺绻绾缁缂缃缇缈缋缌缏缑缒缗缙缜缛缟缡缢缣缤缥缦缧缪缫缬缭缯缰缱缲缳缵幺畿巛甾邕玎玑玮玢玟珏珂珑玷玳珀珉珈珥珙顼琊珩珧珞玺珲琏琪瑛琦琥琨琰琮琬琛琚瑁瑜瑗瑕瑙瑷瑭瑾璜璎璀璁璇璋璞璨璩璐璧"
  + "瓒璺韪韫韬杌杓杞杈杩枥枇杪杳枘枧杵枨枞枭枋杷杼柰栉柘栊柩枰栌柙枵柚枳柝栀柃枸柢栎柁柽栲栳桠桡桎桢桄桤梃栝桕桦桁桧桀栾桊桉栩梵梏桴桷梓桫棂楮棼椟椠棹椤棰椋椁楗棣椐楱椹楠楂楝榄楫榀榘楸椴槌榇榈槎榉楦楣楹榛榧榻榫榭槔榱槁槊槟榕槠榍槿樯槭樗樘橥槲橄"
  + "樾檠橐橛樵檎橹樽樨橘橼檑檐檩檗檫猷獒殁殂殇殄殒殓殍殚殛殡殪轫轭轱轲轳轵轶轸轷轹轺轼轾辁辂辄辇辋辍辎辏辘辚軎戋戗戛戟戢戡戥戤戬臧瓯瓴瓿甏甑甓攴旮旯旰昊昙杲昃昕昀炅曷昝昴昱昶昵耆晟晔晁晏晖晡晗晷暄暌暧暝暾曛曜曦曩贲贳贶贻贽赀赅赆赈赉赇赍赕赙觇觊"
  + "觋觌觎觏觐觑牮犟牝牦牯牾牿犄犋犍犏犒挈挲掰搿擘耄毪毳毽毵毹氅氇氆氍氕氘氙氚氡氩氤氪氲攵敕敫牍牒牖爰虢刖肟肜肓肼朊肽肱肫肭肴肷胧胨胩胪胛胂胄胙胍胗朐胝胫胱胴胭脍脎胲胼朕脒豚脶脞脬脘脲腈腌腓腴腙腚腱腠腩腼腽腭腧塍媵膈膂膑滕膣膪臌朦臊膻臁膦欤欷欹"
  + "歃歆歙飑飒飓飕飙飚殳彀毂觳斐齑斓於旆旄旃旌旎旒旖炀炜炖炝炻烀炷炫炱烨烊焐焓焖焯焱煳煜煨煅煲煊煸煺熘熳熵熨熠燠燔燧燹爝爨灬焘煦熹戾戽扃扈扉礻祀祆祉祛祜祓祚祢祗祠祯祧祺禅禊禚禧禳忑忐怼恝恚恧恁恙恣悫愆愍慝憩憝懋懑戆肀聿沓泶淼矶矸砀砉砗砘砑斫砭砜"
  + "砝砹砺砻砟砼砥砬砣砩硎硭硖硗砦硐硇硌硪碛碓碚碇碜碡碣碲碹碥磔磙磉磬磲礅磴礓礤礞礴龛黹黻黼盱眄眍盹眇眈眚眢眙眭眦眵眸睐睑睇睃睚睨睢睥睿瞍睽瞀瞌瞑瞟瞠瞰瞵瞽町畀畎畋畈畛畲畹疃罘罡罟詈罨罴罱罹羁罾盍盥蠲钅钆钇钋钊钌钍钏钐钔钗钕钚钛钜钣钤钫钪钭钬钯"
  + "钰钲钴钶钷钸钹钺钼钽钿铄铈铉铊铋铌铍铎铐铑铒铕铖铗铙铘铛铞铟铠铢铤铥铧铨铪铩铫铮铯铳铴铵铷铹铼铽铿锃锂锆锇锉锊锍锎锏锒锓锔锕锖锘锛锝锞锟锢锪锫锩锬锱锲锴锶锷锸锼锾锿镂锵镄镅镆镉镌镎镏镒镓镔镖镗镘镙镛镞镟镝镡镢镤镥镦镧镨镩镪镫镬镯镱镲镳锺矧矬"
  + "雉秕秭秣秫稆嵇稃稂稞稔稹稷穑黏馥穰皈皎皓皙皤瓞瓠甬鸠鸢鸨鸩鸪鸫鸬鸲鸱鸶鸸鸷鸹鸺鸾鹁鹂鹄鹆鹇鹈鹉鹋鹌鹎鹑鹕鹗鹚鹛鹜鹞鹣鹦鹧鹨鹩鹪鹫鹬鹱鹭鹳疒疔疖疠疝疬疣疳疴疸痄疱疰痃痂痖痍痣痨痦痤痫痧瘃痱痼痿瘐瘀瘅瘌瘗瘊瘥瘘瘕瘙瘛瘼瘢瘠癀瘭瘰瘿瘵癃瘾瘳癍癞癔"
  + "癜癖癫癯翊竦穸穹窀窆窈窕窦窠窬窨窭窳衤衩衲衽衿袂袢裆袷袼裉裢裎裣裥裱褚裼裨裾裰褡褙褓褛褊褴褫褶襁襦襻疋胥皲皴矜耒耔耖耜耠耢耥耦耧耩耨耱耋耵聃聆聍聒聩聱覃顸颀颃颉颌颍颏颔颚颛颞颟颡颢颥颦虍虔虬虮虿虺虼虻蚨蚍蚋蚬蚝蚧蚣蚪蚓蚩蚶蛄蚵蛎蚰蚺蚱蚯蛉蛏"
  + "蚴蛩蛱蛲蛭蛳蛐蜓蛞蛴蛟蛘蛑蜃蜇蛸蜈蜊蜍蜉蜣蜻蜞蜥蜮蜚蜾蝈蜴蜱蜩蜷蜿螂蜢蝽蝾蝻蝠蝰蝌蝮螋蝓蝣蝼蝤蝙蝥螓螯螨蟒蟆螈螅螭螗螃螫蟥螬螵螳蟋蟓螽蟑蟀蟊蟛蟪蟠蟮蠖蠓蟾蠊蠛蠡蠹蠼缶罂罄罅舐竺竽笈笃笄笕笊笫笏筇笸笪笙笮笱笠笥笤笳笾笞筘筚筅筵筌筝筠筮筻筢筲筱"
  + "箐箦箧箸箬箝箨箅箪箜箢箫箴篑篁篌篝篚篥篦篪簌篾篼簏簖簋簟簪簦簸籁籀臾舁舂舄臬衄舡舢舣舭舯舨舫舸舻舳舴舾艄艉艋艏艚艟艨衾袅袈裘裟襞羝羟羧羯羰羲籼敉粑粝粜粞粢粲粼粽糁糇糌糍糈糅糗糨艮暨羿翎翕翥翡翦翩翮翳糸絷綦綮繇纛麸麴赳趄趔趑趱赧赭豇豉酊酐酎酏"
  + "酤酢酡酰酩酯酽酾酲酴酹醌醅醐醍醑醢醣醪醭醮醯醵醴醺豕鹾趸跫踅蹙蹩趵趿趼趺跄跖跗跚跞跎跏跛跆跬跷跸跣跹跻跤踉跽踔踝踟踬踮踣踯踺蹀踹踵踽踱蹉蹁蹂蹑蹒蹊蹰蹶蹼蹯蹴躅躏躔躐躜躞豸貂貊貅貘貔斛觖觞觚觜觥觫觯訾謦靓雩雳雯霆霁霈霏霎霪霭霰霾龀龃龅龆龇龈龉"
  + "龊龌黾鼋鼍隹隼隽雎雒瞿雠銎銮鋈錾鍪鏊鎏鐾鑫鱿鲂鲅鲆鲇鲈稣鲋鲎鲐鲑鲒鲔鲕鲚鲛鲞鲟鲠鲡鲢鲣鲥鲦鲧鲨鲩鲫鲭鲮鲰鲱鲲鲳鲴鲵鲶鲷鲺鲻鲼鲽鳄鳅鳆鳇鳊鳋鳌鳍鳎鳏鳐鳓鳔鳕鳗鳘鳙鳜鳝鳟鳢靼鞅鞑鞒鞔鞯鞫鞣鞲鞴骱骰骷鹘骶骺骼髁髀髅髂髋髌髑魅魃魇魉魈魍魑飨餍餮饕饔"
  + "髟髡髦髯髫髻髭髹鬈鬏鬓鬟鬣麽麾縻麂麇麈麋麒鏖麝麟黛黜黝黠黟黢黩黧黥黪黯鼢鼬鼯鼹鼷鼽鼾齄滅輸遠驨"
;
export const PINYIN_READ =
  "a,e a,e ai,zhi ai ai ai ai ai ai,yan ai ai ai,yi ai ai ai,e an an an an,yan an an an an,e an ang,hang ang,yang ang ao,wa"
  + " ao ao ao ao ao ao,yu ao,yu ao,yu ba,pa ba,bie ba,pa ba,pa ba,pa ba ba ba ba ba,bo ba,bei ba ba,pa ba,pa ba ba,po ba ba "
  + "bai,bo bai,bo bai,bo bai bai,mo bai bai bai ban ban ban,su ban,pan ban,pan ban ban ban ban,fen ban,pan ban,pan ban ban,p"
  + "an ban ban bang bang bang bang,beng bang,pang bang bang bang,pang bang,beng bang bang,pang bang bao,pao bao,pao bao,pao "
  + "bao bo,bao bao,bo bao bao bao,bu bao bao bao,pao bao bao,pu bao bao bao,bo bei bei bei bei,bi bei bei bei bei bei bei,pe"
  + "i bei bei bei bei bei,bi ben,fen ben ben ben beng beng beng,qi beng,pin beng beng bi bi bi,pi bi bi bi bi bi bi,bie bi b"
  + "i bi bi,yin bi,pi bi bi bi bi bi pi,bi bi bi,bei bi bi bian bian bian bian bian,pian bian,pian bian bian,pan bian,ban bi"
  + "an bian bian biao biao biao,piao biao bie bie bie bie bin,ban bin bin bin bin bin bing bing,ning bing bing bing bing bin"
  + "g bing bing bo bo bo bo bo bo,bei bo bo bo bo bo bo,bai bo bo bo bo,po bo po,bo bo bu bo,bu bu,fu bu bu bu,fou bu bu bu,"
  + "bo bu,pou bu ca cai cai cai cai,zai cai cai cai,kui cai cai cai cai,sa can,sun can,cen can,tian can can can can cang can"
  + "g cang cang cang,zang cao cao cao,zao cao cao,zao ce,si ce ce,ze ce,zha ce ceng ceng cha,zha cha cha,chi cha cha,zha cha"
  + " cha cha,cui cha cha,chai cha chai,che chai,ci chai chan can,chan chan chan chan chan chan chan chan chan,zhan chang cha"
  + "ng chang chang chang zhang,chang chang chang chang,han chang,cheng chang chang chang chao,tiao chao,suo chao chao,zhao c"
  + "hao,zhao chao chao chao,miao chao che,ju che che che che che chen,lan chen chen chen chen chen,dan chen chen chen,zhen c"
  + "hen cheng cheng,chen cheng cheng,deng cheng cheng,kuang cheng,sheng cheng cheng cheng,deng cheng cheng,zheng cheng,ying "
  + "cheng cheng,ping chi,qi chi chi shi,chi chi,tuo chi chi chi chi chi chi chi,che chi chi chi,che chi chong chong chong,hu"
  + "i chong chong chou chou chou chou chou,tiao chou,qiao chou chou,qiu chou chou chou chou,xiu chu chu chu chu chu,chuo chu"
  + " chu chu chu,zhu chu chu chu chu chu chu chu chuai,duo chuan chuan,yuan chuan chuan,zhuan chuan chuan chuan,guan chuang "
  + "chuang,cong chuang,zhuang chuang chuang chuang chui chui chui,duo chui chui,zhui chun chun chun chun,zhen chun,zhun chun"
  + " chun chuo chuo,chao ci,zi ci ci ci ci ci ci ci ci ci,qi ci ci,zi cong cong,chuang cong,chuang cong cong,zong cong cou c"
  + "u cu,zuo cu,chuo cu,chuo cuan cuan cuan cui,zui cui cui cui cui cui,sui cui,zu cui cun cun cun cuo cuo,zuo cuo,chai cuo,"
  + "ze cuo,zuo cuo da,ta da,ti da da da da,dai dai,bao dai,e dai dai dai dai dai dai dai dai dai,di dai,yi dan dan,jie dan d"
  + "an,chan dan dan,shan dan,tan dan dan dan,tan dan dan,yan dan dan,tan dan dang dang dang dang dang dao,diao dao dao dao d"
  + "ao dao dao dao dao dao dao dao de de,dei de,di deng deng,ding deng,de deng deng deng deng,shan di,ti di di di di,hua di "
  + "di,ti di di,zhai di di,zhi di,de di,de di di di di,ti di di dian dian dian,tian dian dian dian,tian dian dian dian dian,"
  + "tian dian,tian dian dian dian,ting dian dian diao diao diao diao diao diao,nuo diao diao diao,tiao die,tu die die,she di"
  + "e,tie die,yi die die ding,zheng ding,cheng ding ding ding ding,zhen ding ding ding diu dong dong dong,zhong dong dong do"
  + "ng dong,tong dong,tong dong dong,tong dou dou dou,zhu dou dou dou,zhu dou dou,du du du,dai du du du,dou du,zhe du du du,"
  + "tu du du du,duo du du duan duan duan duan duan duan dui,zui dui,rui dui dui dun dun,tun dun,zun dun,dui dun,du dun,tun d"
  + "un dun,shun dun,qun duo,zhuo duo,chi duo duo duo duo duo duo duo duo duo,tuo duo,hui e,yi e e e e e e e,wu e e e e e en "
  + "er,neng er,ren er,reng er er er er er fa fa fa fa fa fa fa fa fan fan fan,pan fan fan fan fan fan,po fan fan fan fan fan"
  + " fan fan fan fan,feng fang fang fang,pang fang fang,pang fang fang fang,pang fang fang fang fei fei fei,pei fei fei,bi f"
  + "ei,fen fei fei fei,pei fei fei,fu fei fen fen fen,pen fen fen fen fen fen fen,pen fen fen,kang fen,bin fen fen fen feng "
  + "feng,bian feng feng feng feng feng feng feng feng,peng feng,ping feng feng feng feng fu,fo fou,pi fu fu fu fu fu,pu fu,b"
  + "i fu fu,bi fu fu fu fu fu,bi fu fu,pou fu fu fu fu,pu fu fu fu fu fu pu,fu fu fu fu fu fu,pi fu fu fu fu fu fu fu fu fu "
  + "fu fu fu,bu fu fu fu ga,ge ga gai gai gai,gui gai gai,ge gai,xie gan,an gan,han gan gan,qian gan gan gan,qian gan,han ga"
  + "n gan gan gang gang gang gang gang gang gang gang,hong gang,gong gao gao,hao gao gao gao gao gao,qiao gao,hao gao gao,ju"
  + " ge ge ge ge ge ge,ga ge,yi ge ge,ji ge ge,luo ha,ge ge ge,rong ge ge,gan ge gei,ji gen gen geng geng geng geng,lang gen"
  + "g geng geng gong gong gong gong gong gong gong gong gong gong gong gong gong,ju gong gong,hong gou gou gou gou gou gou g"
  + "ou gou gou gu gu gu gu gu gu gu gu gu gu,ku gu gu gu,lu gu gu gu gu gu,hu gua gua gua gua gua gua guai guai guai guan gu"
  + "an guan guan guan guan guan guan guan guan,huan guan guang guang,yan guang,kuang gui gui gui gui,he gui gui,jun gui gui "
  + "gui gui gui gui gui,ju gui gui gui gun gun gun,hun guo guo guo guo,luo guo guo ha,he hai,gai hai hai hai hai,jie hai,he "
  + "hai han han han han han han han han han,kan han han han han,xian han han,dan han han han,gan han hang,ben hang,kang hang"
  + " hao hao hao hao hao,shi hao hao,mao hao,xiao hao,gao he,ha he,ye he he,ge he,hu he he,hu he he,ge he,an hao,he he he he"
  + " he,shi he he he hei,mo hei hen,gen hen hen,yan hen heng,hng heng,xiang heng,guang heng heng hong hong hong hong,jiang h"
  + "ong hong hong hong hong,gong hou hou hou hou hou hou hou hu,xiao hu hu hu hu hu hu hu hu hu hu hu hu hu,xiao hu hu hu hu"
  + " hua hua hua hua hua,gu hua hua,guo hua,huo hua huai huai,hui huai,fu huai huai,pi huan huan huan hai,huan huan huan hua"
  + "n huan huan,tuan huan huan huan,hui huan huan huang,kang huang huang huang,kuang huang huang huang,wang huang huang huan"
  + "g huang huang huang,guang huang hui hui hui hui hui hui hui hui hui hui hui hui hui hui hui hui,kuai hui hui hui hui hui"
  + " hun,xun hun hun hun hun hun,gun huo,hua huo,guo huo huo huo huo,yu huo huo,he huo huo ji ji,jie ji ji,wei ji,qi ji,qi j"
  + "i,zhi ji ji ji ji ji,jiao ji ji ji,yi ji ji,qi ji ji ji ji ji,jie ji ji ji ji ji ji ji ji ji ji ji ji,qi ji ji,qi ji ji "
  + "ji,zhi ji,zhai ji ji ji ji ji ji ji ji,xi ji ji ji ji ji jia jia jia,ga jia jia,jie jia jia jia jia,gu jia jia jia,jie j"
  + "ia jia,jie jia jia jia jian jian jian jian jian jian jian jian jian,xian jian jian,gan jian jian,chong jian jian jian,xi"
  + "an jian jian jian jian jian jian jian jian kan,jian jian jian jian jian,xian jian jian jian,mou jian jian jian jian jian"
  + " jian jian jian jiang jiang jiang,qiang jiang jiang jiang jiang jiang jiang jiang jiang jiang jiang,xiang jiao,qiao jiao"
  + " jiao jiao,qiao jiao,xiao jiao jiao jiao jiao jiao jue,jiao jiao jiao jiao jiao,yao jiao,jue jiao,xiao jiao,jue jiao jia"
  + "o,zhuo jiao jiao,chao jiao jiao jiao jiao jiao jiao,zao jie,qi jie,xie jie jie,ji jie jie jie jie jie ju,jie jie jie,qie"
  + " jie,she jie jie,ji jie jie,xie jie,ju jie ji,jie jie,gai jie jie jie,ge jie jie jie jin jin,qian jin jin jin jin jin ji"
  + "n jin jin,fu jin jin jin jin jin jin jin jin,qin jin jin,jing jing jing jing jing jing jing jing jing,liang jing,qing ji"
  + "ng jing jing jing jing,ying jing,geng jing jing jing jing jing jing jing jing jing jing,cheng jiong jiong jiu jiu jiu ji"
  + "u jiu jiu jiu jiu jiu jiu jiu jiu jiu jiu jiu,gao jiu jiu ju,qu ju,gou ju ju ju,ji ju ju ju ju,zui ju ju ju,jian ju ju j"
  + "u ju,qu ju ju ju ju ju ju,gou ju ju ju juan,yuan juan juan juan juan juan,quan juan jue,gui jue jue jue,ku jue jue jue,j"
  + "iao jue jue jue jun,yun jun jun jun jun jun jun,shun jun jun,xun jun jun ka,ke ka,ga ka,qia ge,ka kai kai,jia kai,jie ka"
  + "i kai kan kan,chen kan kan kan kan kang kang kang kang,gang kang,gang kang,gang kang,hang kao kao kao kao ke,jiong ke,he"
  + " ke ke,kuan ke ke ke ke,qiao ke,hai ke,ge ke,jie ke ke,kei ke,qia ke ken ken ken,yin ken keng,kang keng,hang kong kong k"
  + "ong kong,qiang kou kou kou kou ku,gu ku ku ku,gu ku ku ku kua kua kua,ku kua,ku kua kuai,yue kuai kuai kuai kuan kuan,xi"
  + "n kuang,wang kuang kuang,jue kuang kuang kuang kuang kuang kui,yu kui kui kui kui kui kui,kuai gui,kui kui kui kui,hui k"
  + "un kun,hun kun,hun kun kuo,gua kuo kuo kuo la la la la,qu la,xi la la lai lai lai lan,la lan lan lan lan lan lan lan lan"
  + " lan lan lan lan lan lan lang lang lang,hang lang lang lang lang lao lao lao,lou lao lao,liao lao,mu lao,luo lao,luo lao"
  + " lei,le le,yue lei lei lei lei lei,lv lei lei lei le,lei lei lei leng,ling leng leng,ling li,chan li li li li li li,chi "
  + "li li li li li li li,chi li li li,lie li li li li li li li li,lie li li li,wei li li li,dai li li li,mai lia,liang lian "
  + "lian lian lian lian lian,ling lian lian,chen lian lian lian lian lian lian liang liang liang liang liang liang liang lia"
  + "ng liang liang liang liao,lao liao,liu liao,lao liao liao liao liao lao,liao le,liao liao liao liao liao lie,li lie lie "
  + "lie lie,xi lin lin lin,ling lin lin lin lin lin lin lin lin lin,ling ling ling ling,lian ling ling ling ling ling ling l"
  + "ing ling ling ling ling,lian liu liu liu liu,chu liu liu liu liu liu liu liu,lu long long long long long long long long "
  + "long lou lou lou lou lou lou lu,hu lu lu lu lu lu lu,xi lu lu lu lu,liu lu,lou lu,luo lu lu,lv lu lu lu lu,liu lu lv lv "
  + "lv lv lv lv lv lv lv,bi lv lv lv,shuai lv lv,lu luan luan luan luan luan,kun luan lve lve lun lun lun lun lun lun,guan l"
  + "un luo luo luo luo luo luo luo luo luo,la luo luo luo,lao ma ma ma ma ma ma ma ma ma mai,man mai mai mai mai mai,mo man "
  + "man man man man,wan man man man man mang,huang mang,huang mang mang,meng mang mang mao,miao mao mao mao mao mao mao mao "
  + "mao,mo mao mao,mo mao me,yao mei mei mei mei mei mei mei,mo mei mei mei mei mei mei,wen mei mei mei men men men meng,min"
  + "g meng meng meng,ming meng meng meng meng mi mi mi,ma mi,mei mi mi,mei mi mi mi,bi mi mi,bi mi mi mi mian mian,min mian "
  + "mian mian,wen mian mian,wan mian mian miao miao,mao miao miao,mo miao miao miao miao mie mie min min min,ming min min mi"
  + "n ming,meng ming ming ming ming ming miu mo mo mo mo,mu mo mo mo,ma mo mo,ma mo,me mo,mu mo,mei mo mo mo mo mo mou mou,m"
  + "u mou,mei mu mu mu mu mu,wu mu mu mu,man mu,bo mu mu mu mu mu mu na na,ne na,ne na na,nuo na,nuo na nai nai,ai nai nai,n"
  + "eng nai nan,na nan nan nang nao nao nao nao nao,zhao ne,ni nei nei,na nen neng,tai ni ni ni,nie ni,nie ni ni ni ni,te ni"
  + " ni ni,ruo nian,yan nian,dian nian,ning nian nian nian,nie nian niang niang niao,diao niao,sui nie nie nie nie nie nie n"
  + "ie nin ning,chu ning ning ning,zhu ning ning,zhu niu niu,chou niu niu nong nong nong nong,long nu nu nu nv,ru nuan,xuan "
  + "nve nve,yao nuo nuo nuo nuo o,e ou ou ou ou ou ou ou pa pa pa pa,mo pa,bo pa pai,bo pai,bai pai pai pai,ba pai,mai pan p"
  + "an,bo pan pan pan,fen pan pan pan pang pang pang,peng pang pang,pan pao pao pao,bao pao,bao pao,bao pao,bo pao pei pei p"
  + "ei,pou pei,fei pei pei pei pei pei pen pen peng,ping peng,beng peng peng peng,pang peng peng peng peng peng peng peng pe"
  + "ng,feng peng pi,huai pi pi pi pi pi pi pi pi pi,pai pi pi pi pi pi pi pi pian pian pian,pan pian piao piao,biao piao pia"
  + "o pie,bie pie,bi pin,bing pin pin pin pin,ping ping ping ping,peng ping ping,pian ping ping ping ping,bing po po po po p"
  + "o po,bo po,pai po pou,po pu,pi pu pu pu,fu pu,bei pu,bei pu,bo pu,bu pu,piao pu pu pu pu pu,bao pu,bao qi,ji qi qi,xi qi"
  + ",cu qi qi qi qi,qie qi qi,qie qi,ji qi,ji qi,ji qi qi qi,yi qi qi,ji qi qi,gui qi,zhi qi qi qi,kai qi qi qi qi,xie qi,qi"
  + "e qi qi qi qi qi,gai qi,li qi qia qia qia,he qian qian qian qian,yan qian qian qian qian qian qian,gan qian qian qian qi"
  + "an,jian qian qian qian,jian qian qian qian,han qian qian qiang qiang qiang,kong qiang qiang qiang qiang,jiang qiang qiao"
  + " qiao qiao qiao qiao qiao qiao qiao qiao qiao,shao qiao qiao qiao qiao,xiao qiao qie,qi jia,qie qie,ju qie qie qin qin q"
  + "in,qing qin qin qin,qi qin qin qin qin qin qing,jing qing qing qing qing qing qing qing qing qing qing qing qing qiong q"
  + "iong qiu qiu qiu qiu qiu qiu qiu qiu,you qu qu,ou qu,ju qu qu qu,jue qu qu,ju qu qu,ju qu qu,cu qu quan,juan quan quan q"
  + "uan,chuo quan quan quan quan quan quan,xuan quan que,kui gui,que que que que que que que,qiao qun qun ran ran ran,nan ra"
  + "n rang rang rang,ning rang rang rao rao,you rao re,ruo re ren ren ren ren ren ren,lin ren ren ren ren reng reng ri rong,"
  + "reng rong rong rong rong rong rong rong,yong rong rong rou rou rou,ru ru ru ru ru ru ru ru ru ru ru,nu ruan ruan,yuan ru"
  + "i,juan rui rui run run ruo,re ruo sa sa,xi sa sai sai sai,se sai san san san san sang sang sang sao sao sao sao se se,sh"
  + "ai se sen seng,ceng sha,suo sha sha sha,cha sha,suo sha sha sha sha shai shai shan shan,tian shan,sha shan shan shan sha"
  + "n shan shan shan shan shan shan shan,shuan shan shan shang shang shang shang shang shang shang,chang shang,chang shao,xi"
  + "ao shao,xiao shao shao shao,xiao shao,shuo shao shao shao,sao shao shao she she she,yi she,gua she,shi she,ce she she,ye"
  + " she she,die she she shen shen shen shen shen,juan shen shen shen shen shen,chen shen shen shen shen shen,zhen shen shen"
  + "g,qing sheng sheng sheng sheng sheng sheng,xing sheng,cheng sheng sheng,xing sheng,ku shi shi,yi shi shi,yi shi shi shi "
  + "shi shi shi,dan shi,she shi shen,shi shi,si shi shi shi,zhi shi shi shi shi,xi shi shi shi,te shi,qi shi shi shi shi,zi "
  + "shi shi shi shi shi,ti shi shi shi,kuo shi shi shi shi shi,zhi shi,fu shi,zhi shi shi shi shou shou shou shou shou shou "
  + "shou,shu shou,dao shou shou shu shu shu shu shu shu shu shu,yu shu,chu shu shu shu shu shu,shou shu shu shu shu shu shu "
  + "shu shu,zhu shu,zhu shu shu shu shu shu shu,ye shu,zhu shu,shuo shu shu shua shua shuai shuai,suo shuai shuai shuan,quan"
  + " shuan,quan shuang shuang shuang shui,shei shui shui shui,tuo shun shun shun shun shuo,shui shuo shuo shuo si,shi si,xi "
  + "si si,sai si si,ci si si si,ti si,shi si si ci,si shi,si si si,yi song song song song song song song song sou,xiao sou s"
  + "ou sou,shuo su su su su su su su su su,shuo su,xiu su su suan suan suan sui sui,duo sui sui sui sui sui sui sui sui,zhui"
  + " sui sun sun sun suo,sui suo,xun suo,shua suo,su suo suo suo suo ta,da ta,tuo ta,tuo ta,jie ta,da ta ta ta ta tai tai ta"
  + "i,chi tai,yi tai tai tai,ta tai tai tan tan tan tan tan tan tan,shan tan tan,xun tan tan tan tan tan,zhan tan tan,xian t"
  + "an,yi tan tang,shang tang tang tang tang tang tang tang tang,chang tang tang,chang tang,zheng tang tao tao tao tao tao t"
  + "ao,tiao tao tao tao,yao tao tao te teng teng teng teng ti ti ti,die ti ti,di ti ti,di ti ti,ben ti ti ti ti ti ti tian t"
  + "ian tian,chen tian tian tian tian,tan tian tiao,tao tiao tiao tiao tiao,diao tie tie tie ting ting,yin ting ting,ding ti"
  + "ng ting ting ting ting ting tong tong,dong tong,dong tong tong tong tong tong,zhong tong tong tong,dong tong tong tou to"
  + "u,dou tou tou,shu tu tu tu tu tu tu tu,chu tu tu,du tu tu,chan tuan,zhuan tuan,qiu tui tui tui tui,yue tui,tun tui tun,t"
  + "ian tun,zhun tun tuo,chi tuo tuo,tui tuo tuo,duo tuo,duo tuo tuo tuo tuo,ta tuo wa wa,gui wa,jue wa,gui wa,gui wa wa,mo "
  + "wai wai wan wan wan wan wan wan wan wan,kuan wan wan wan wan,huan wan wan,yuan wan wan,mo wan wang,hong wang,yu wang,wu "
  + "wang,kuang wang wang wang wang wang wang wei wei wei wei wei wei wei,gui wei wei wei wei wei wei wei wei wei wei wei wei"
  + ",yi wei wei wei,yu wei,mei wei wei wei wei wei,li wei wei wei,yu wei wei wen,wo wen,yun wen wen wen wen wen wen wen wen "
  + "weng weng weng wo,zhua wo wo,guo wo wo wo,guan wo wo,ou wo wu wu wu wu wu wu wu wu,mo wu wu,yu wu,yu wu,tun wu,mou wu wu"
  + " wu wu wu wu wu wu wu wu wu wu wu,mo wu wu wu xi,cuo xi,yi xi,si xi xi xi xi xi xi xi xi xi xi xi xi xi xi,yi xi xi xi x"
  + "i,qi xi xi xi xi xi xi xi xi,chi xi,xian xi,xian xi,ji xi xi,hu xi xia xia,ha xia xia xia xia,jia xia xia xia xia sha,xi"
  + "a xia,jia xia,he xian,hen xian xian xian xian xian,qian xian,jian xian xian xian xian xian,yan xian xian xian xian xian "
  + "xian xian xian xian xian,yan xian,xiong xian xian,wen xian xiang xiang xiang xiang xiang xiang xiang xiang xiang xiang x"
  + "iang xiang xiang xiang xiang xiang,hang xiang xiang xiang xiang xiao xiao,qiao xiao xue,xiao xiao,xue xiao,ao xiao xiao "
  + "xiao xiao xiao xiao xiao xiao,jiao xiao xiao xiao xiao xie xie,suo xie,ya xie,he xie,wa xie xie,jia xie xie,ya xie,xia x"
  + "ie xie xie xie xie xie xie xie,yi xie xie xie xin xin xin xin xin xin xin xin xin,shen xin xing xing xing xing xing xing"
  + " xing xing xing,geng xing,hang xing,cheng xing,nie xing xing xing,sheng xiong,kuang xiong xiong xiong xiong xiong xiong "
  + "xiu,xu xiu xiu xiu xiu xiu xiu xiu xiu xu xu,qu xu,nuo xu xu,shi xu xu xu,hu xu xu xu xu xu chu,xu xu xu,chu xu xu xu xu"
  + "an xuan xuan xuan xuan xuan xuan xuan xuan,huan xuan xue xue xue xue,jue xue xue,xie xun xun xun xun,jun xun xun,xin xun"
  + " xun,yan xun xun xun xun xun xun ya ya,xia ya ya ya,xia ya ya ya ya ya ya,yu ya ya ya ya ya yan,yi yan,ye yan yan,yin ya"
  + "n yan yan yan,xing yan,dan yan yan yan,yin yan yan yan,tan yan yan yan yan,wen yan yan yan yan yan yan yan yan yan yan,p"
  + "an yan yan yan yan yang yang,ying yang yang yang yang yang yang yang yang,xiang yang yang yang,ang yang yang yang yang y"
  + "ao yao yao,jiao yao yao yao yao yao yao yao,tiao yao,jiao yao yao yao yao ye ye,yi ye,xie ye ye,shu ye ye,yi ye ye ye ye"
  + ",xie ye ye ye ye,shi yi yi,yin yi yi,ji yi yi yi yi yi yi yi,wei yi,chi yi yi yi,ning yi,yin yi yi yi yi yi yi,ji yi,si "
  + "yi,jue yi,xian yi,si yi yi yi yi,e yi,ge yi yi yi yi yi,si yi yi yi yi yi yi yi yi yi yi yi yi yi yi yi yi yi yin yin yi"
  + "n yin,yan yin yin yin yin,jin yin yin,yan yin yin yin,yun yin yin yin,yi ying,yang ying ying ying ying ying ying ying yi"
  + "ng ying ying ying ying ying ying ying ying,geng ying,yang yo yong yong yong yong yong yong yong yong yong yong yong,chon"
  + "g yong yong,tong yong yong you you you you you you,yao you you you you you,liu you you,wei you you you you you you you,y"
  + "ao yu yu yu,wei yu yu yu yu yu yu,tu yu,shu yu,dou yu yu,tou yu yu yu yu,zhu yu yu yu yu yu yu yu yu,hu yu yu yu,xu yu x"
  + "u,yu yu,yong yu yu yu,ya yu yu yu yu,zhou yu yu yu yu yu yu,xie yu yuan yuan yuan yuan yuan yuan yuan yuan,huan yuan yua"
  + "n,wan yuan,yun yuan yuan yuan yuan yuan yuan,yu yuan yuan,yun yuan yue yue,yao yue,huo yue yao,yue yue yue yue,ru yue yu"
  + "e yun yun yun yun,jun yun yun,yuan yun yun yun yun yun yun za za za,duo zai zai zai zai zai zai zai zan,za zan,cuan zan "
  + "zan zang zang zang zao zao zao,zuo zao zao zao zao,cao zao,zhao zao zao zao,cao zao zao zao,sao ze ze,zhai ze ze zei zen"
  + " zeng,ceng zeng ceng,zeng zeng zha,za zha,cha zha zha,ya ya,zha zha zha zha zha,shan zha za,ze zha,zuo zha zha zhai zhai"
  + " zhai,che zhai zhai zhai,se zhan zhan zhan,dan zhan,nian zhan,tian zhan zhan nian,zhan zhan zhan zhan zhan zhan,tie zhan"
  + " zhan zhan,chen zhan zhang zhang zhang zhang zhang zhang zhang zhang zhang zhang zhang zhang zhang zhang zhang zhao,qiao"
  + " zhao zhao,hua zhao zhao zhao zhao zhao zhao zhao,shao zhe zhe,she zhe zhe zhe zhe zhe zhe zhe,zhei zhe zhen zhen zhen z"
  + "hen,juan zhen zhen zhen zhen zhen zhen,chen zhen,chen zhen zhen,shen zhen zhen zhen zheng zheng zheng zheng zheng zheng "
  + "zheng zheng zheng zheng zheng zhen,zheng zheng zheng zheng zhi zhi,qi zhi,qi zhi,zi zhi zhi zhi,shi zhi zhi,xie zhi,zhu "
  + "zhi zhi zhi zhi zhi,shi zhi zhi zhi zhi zhi zhi zhi zhi zhi zhi zhi zhi zhi zhi,die zhi,zhui zhi zhi zhi,shi zhi zhi zhi"
  + " zhi zhi zhi zhi zhi zhi,chi zhi,die zhong zhong,chong zhong zhong zhong zhong zhong,chong zhong zhong,chong zhong zhong"
  + ",yin zhou zhou zhou zhou zhou zhou,yu zhou zhou zhou zhou zhou zhou zhou zhou zhu zhu zhu zhu,shu zhu zhu zhu zhu,di zhu"
  + " zhu,chong zhu zhu zhu zhu zhu zhu,zhuo zhu zhu,chu zhu zhu zhu zhu zhu zhu,zhou zhu,zhou zhu zhua zhao,zhua zhuai,ye zh"
  + "uan zhuan zhuan,zhuai zhuan,xuan zhuan,zuan zhuan zhuang zhuang,peng zhuang zhuang zhuang zhuang zhuang chui,zhui zhui z"
  + "hui,dui zhui zhui zhui zhun zhun zhuo zhuo zhuo zhuo zuo,zhuo zhuo,zhu zhuo zhuo,zhou zhe,zhao zhuo zhuo zi,ci zi zi zi "
  + "zi,ci zi zi zi zai,zi zi zi zi zi zi zi zong zong zong zong zong,zeng zong zong zou zou zou,cou zou,cou zu,ju zu,ju zu,c"
  + "u zu,sou zu,jie zu zu,zhu zu zuan zuan zui zui zui,cuo zui zun zun zuo zuo zuo zha,zuo zuo zuo zuo zuo chu ji,qi wu gai "
  + "nian sa pi gen,xuan cheng,sheng ge,li nao e gun yu pie,yi bi,pin tuo,zhe yao,wo yao,xiao zhi di,zhi xin yin kui,qiu yu g"
  + "ao,hao tao zhu ji,qi nai mie,nie ji qi mi bei,bo se gu,jia ze she cuo,ji yan jue si ye yan fang po gui kui,gui bian ze g"
  + "ua you dao yi wen jing ku,kou gui kai la ji shan,yan wan kuai piao,biao jue qiao huo,hua yi jiong wang ren ding zhang le"
  + ",li sa ge,yi mu ren yu pi,bi ya wa wu chang cang,chen kang,gang zhu ning ka you yi,die gou,kou tong tuo,yi ni ga,jia ji "
  + "er,nai you kua,hua kan zhu,zhou yi tiao,diao chai jiao,xiao nong mou,mao chou yan li qiu li yu ping yong qi,si feng,beng"
  + " qian,qing ruo,re pai zhuo shu luo wo,wei bi,bei ti,diao guan kong ju fen yan xie,jie ji,jie wei zong,cong lou,lv tang b"
  + "in nuo chi xi jing jian,zen jiao jiu tong,zhuang xuan dan,shan tong tun,qiu she qian zu yue cuan di,za xi xun,zhuan hong"
  + " guo,xu chan kui bao pu hong,jun fu fu su si tou yan bo gun mao,mou xie luan,ji pou,bao bing ying luo,guo lei,lian bing "
  + "hu lie xian,sheng song mi zhong ming,mian yan jie hong shan ou ju ne gu he di zhao qu yi kuang lei gua ji,jie hui shen g"
  + "ou quan zheng hun xu qiao gao kuang ei zou zhuo wei yu shen chan sui chen jian xue ye e yu xuan an di zi pian mo dang su"
  + " shi mi zhe jian zen qiao jue yan zhan chen jie jin fu wu,wei qian jing ban dian,yan zuo bei,pi xing gai zhi,de nie zou,"
  + "zhe chui pi,bi wei huang kui,wei xi,xie han qiong kuang mang wu fang bing pi bei ye,qiu di tai jia zhi,ji zhu kuai qie,x"
  + "i huan,xun yun li ying,cheng gao xi,chi fu pi tan yan juan yan yin zhang po,pi shan zou,ju ling feng chu huan mai qu sha"
  + "o he,kai ge meng xu,mao xie sou,xiao xie jue yin qian,kan dang chang si,mou bian,pan ben qiu ben e,sheng fa shu ji yong,"
  + "weng he,huo wei,xu wu ge,yi zhen,quan kuang pi yi li qi,yin ban gan long dian,zhen lu che chi,di tuo,yi ni mu,mei ao,you"
  + " ya die dong,tong kai shan,yan shang,jiong nao gai yin,ken cheng shi guo xun lie yuan,huan zhi an,yan yi pi,bi nian,dian"
  + " peng,beng tu sao dai ku die yin leng hou ge yuan man yong liang chi xin pi yi cao jiao,qiu nai,reng du qian ji wan qion"
  + "g,xiong qi xiang fu yan,yuan yun fei,fu ji li e ju,qu pi,bi zhi rui,ruo xian chang cong qin,yin wu,hu qian qi,chi shan,w"
  + "ei bian zhu kou yi mo gan pie,pi long ba,pei mu ju,cha ran qing chi fu,pu ling,lian niao yin mao ying qiong min shao,tia"
  + "o qian,xi ti,yi rao bi ci,zi ju tong hui zhu ting qiao fu ren xing quan,chuo hui xun ming ji,qi jiao,xiao chong jiang lu"
  + "o xing,ying xun,qian gen,jian jin mai sun hong zhou kan bi shi wo you,xiu e mei you,diao li tu,cha xian fu,piao sui,wei "
  + "you di shen,xin guan,wan lang,liang ying chun jing qi,ji xi,si song jin,qin nai qi ba shu,jiao chang tie yu huan,zhui bi"
  + ",pi fu tu dan cui yan,yu ju,zu dang jian,guan wan,yu ying gu han qia feng ren,shen xiang wei chan kai qi kui xi e bao pa"
  + " ting,ding lou pai xuan jia,xia zhen,qin shi ru mo en bei weng hao,gao ji li bang,pang jian shuo lang ying yu su meng do"
  + "u xi lian cu,cou lin qu kou xu,su liao,lu hui xun,tan jue rui zui,jue ji,qie meng,mang fan,bo qi hong xie hong wei yi we"
  + "ng,yong sou bi,bo hao tai ru xun xian gao li huo,he qu,ju heng fan nie,bo mi gong yi kuang lian da,zhe yi xi zang,zhuang"
  + " pao you,wang liao,niao ga gan shou men tuan chen,shen fu,bu pan,bian ao,niu jie,jia jiao za,zan yi lv,luo jun tian ye a"
  + "i na ji,yi guai,guo bai,ba ju pou,fu lie,li qian guan die,she zha ya qin yu,chou an,yan xuan bing kui yuan,chuan shu en "
  + "chuai,chi jian,lian shuo zhan nuo sang luo ying zhi han,qian zhe,la xie lu zun cuan gan huan,juan pi,bo xing zhuo huo,qu"
  + "e zuan nang yi te,tui dai shi bu,ji chi,hua ji,jiao kou dao,tao le,li zha ya,a yao fu wu,m yi dai,tai li e,ai bi,pi bei,"
  + "bai guo qin yin,shen za ka,nong ga,xia gu,gua ling dong ning duo nao,na you si kuang,qiang ji,xi shen hui,hai da lie yi,"
  + "xi xiao bi ci,zi guang,gong hui,yue xiu,xu yi pai,gu kuai duo ji mie mi,mie zha nong gen,hen mou ma,mai chi,xia lao geng"
  + ",ying wu,ng zha suo zao xi,xie zuo,shi ji,jie feng,beng ze nuo,re miao lin,lan zhuan zhao,zhou tao hu cui,zu sha,qie yo,"
  + "yu dan bo ding lang li shua chuai,chuo die,zha da,ta nan li kui jie,xie yong,yu kui,huai jiu sou,su yin chi,di jie,jue l"
  + "ou ku o,wo hui,zhou qin ao su du ke,he nie he chen,tian suo ge a,sha n,ng hao die,dia ai ai,yi suo,shuo hai,hei tong chi"
  + " pei lei,le cao piao qi,zu ying beng sou di,zhe mi peng jue liao pu chuai,zuo jiao,jiu o,yu qin lu ceng,cheng deng hao j"
  + "in jue,xue yi,ai sai pi ru ca,cha huo,xue nang wei,guo jian,nan nan,nie lun hu ling you yu qing yu huan,yuan wei zhi pei"
  + ",pi tang,nu chou,dao ze guo wei wo man zhang fu fan ji qi qian qi qu ya,xia xian ao cen lan ba hu ke dong jia xiu dai go"
  + "u mao min yi dong,tong jiao,qiao xun zheng lao lai song yan gu xiao,yao guo kong jue,yu rong yao wai,wei zai wei yu cuo,"
  + "ci lou zi mei sheng,cheng song ji zhang lin deng bin,ban yi,ni dian chi,fu pang,fang cu xun yang hou lai xi,si chang hua"
  + "ng yao zheng,zhi jiao,yao qu shan,xian quan qiu an,han guang ma niu,nv yun xia pao fei rong kuai shou sun bi juan li yu "
  + "xian yin suan,xun yi,ji guo,luo luo ni she cu mi hu cha wei wei mei nao zhang jing jue liao,lao xie,ha xun huan,quan chu"
  + "an huo sun yin zhi,zhong shi tang,xing tun xi ren yu chi yi xiang bo yu hun cha,zha sou mo xiu jin san zhuan nang pi wu "
  + "gui pao xiu xiang tuo an,yan yu bi,pi geng ao jin,qin chan xie lin ying xin dao cun chan,qian wu zhi,qi ou chong wu kai,"
  + "qi chang chuang song,zhong bian niu hu,tie chu,xu peng da,dan yang zuo,zha ni fu,fei chao yi yi tong yan ce kai xun,shun"
  + " ke yun bei song qian kui,li kun yi ti quan,xun qie xing fei chang,tang wang chou,qiu hu cui yun,wen kui e leng zhui,chu"
  + "an qiao,qiu bi su qian,qie yong jing qiao chong,zhuang chu lin,lan meng tian hui shuan yan wei hong min kang ta lv kun j"
  + "iu lang yu chang xi wen hun e,yan qu que he tian que han,kan qiang pan,qiang qiang,zang shui qi si cha feng yuan mu mian"
  + " dun,zhuan mi gu,yu bian wen,min hang,kang wei le gan,han shu long,shuang lu yang si tuo ling mao,liu luo,po xuan,juan p"
  + "an tuo,duo hong min,mian jing huan wei lie jia zhen yin,yan hui zhu ji xu,yi hui,kuai tao,yao xun,xuan jiang,hong liu hu"
  + ",xu xun ru su,sou wu lai wei zhuo juan,yuan cen,qian bang,bin xi mei huan zhu qi xi song du zhuo pi,pei mian,sheng gan,h"
  + "an fei cong,shuang shen guan lu shuan,shua xie,die yan,yin mian jiao,qiu sou,shao huang,kuang xu pen jian,zan xuan wo,ou"
  + " mei yan qin,zhen ke,kai she mang ying pu,fu li ru ta hun bi xiu,chou fu tang pang,peng ming,mi huang,guang ying xiao la"
  + "n cao hu luo,ta huan lian zhu yi lu xuan gan,han shu,zhu si shan shao tong,chong chan lai sui li dan,tan chan,dan lian,x"
  + "ian ru,ruan pu bi,pi hao zhuo,shuo han xie ying yue,yao fen hao ba mian gui dang mi,fu you chen ning qian qian wu liao q"
  + "ian huan,xian jian jian chuo ya wu jiong ze,zuo yi,tuo er jia,xie jing dai hou pang,feng bu li qiu xiao ti qun,xun kui w"
  + "ei huan lu,dai chuan huang qiu xia ao gou ta liu xian lin ju,qu xie miao sui la,lie ji hui,sui tuan,shi zhi kao zhi ji e"
  + " can,chan xi ju chan jing nu mi fu,bo bi yu,zhou che,cao shuo,yue fei,pei yan wu yu bi jin,xian zi gui niu,hao yu si da "
  + "zhou,chou shan qie ya rao shu luan jiao,xiao pin cha li ping,pin wa xian suo di wei e jing biao jie,qie chang bi chan nu"
  + ",nv ao,yun yuan ting wu,mou gou mo pi,bi ai pin chi li yan qiang piao,biao chang lei zhang xi shan,chan bi niao ma,mo sh"
  + "uang ga ga fu nu zi jie jue bao zang si fu zou yi nu dai,tai xiao hua pian li qi ke zhui can zhi wu ao liu shan biao,pia"
  + "o cong chan ji xiang si yu zhou ge,he wan kuang yun pi shu gan xie fu zhou fu chu dai ku hang jiang geng xiao ti ling qi"
  + " fei shang gun duo shou liu quan wan zi ke xiang ti miao hui si bian,pian gou zhui min jin zhen ru gao li yi jian bin pi"
  + "ao man lei mou,miao sao xie liao zeng jiang qian qiao,sao huan zuan yao,mi ji chuan,shun zai,zi yong ding ji wei bin,fen"
  + " wen,min jue ke long dian dai po min jia er gong xu ya hang,heng yao luo,li xi hui,hun lian qi ying qi hu kun yan cong w"
  + "an chen ju mao yu yuan,huan xia nao ai tang jin huang ying cui cong xuan zhang pu can qu lu bi zan wen wei yun tao wu,wo"
  + " biao,shao qi cha ma li pi,bi miao yao rui,nen jian chu cheng cong,zong xiao fang,bing pa,ba zhu,shu nai zhi zhe long ji"
  + "u ping lu xia,jia xiao you,zhou zhi tuo zhi ling gou,ju di,chi li,yue duo,tuo cheng,jue kao lao ya rao zhi zhen guang qi"
  + " ting gua,tian jiu hua heng,hang gui,hui jie luan juan,quan an xu,yu fan gu,jue fu jue zi suo ling chu,zhu fen du qian z"
  + "hao,zhuo luo chui,duo liang guo jian di,ti ju zou,cou shen,zhen nan zha,cha lian lan ji pin ju qiu duan chui,zhui chen l"
  + "v cha ju xuan mei ying zhen fei ta sun xie gao cui gao,kao shuo bin,bing rong zhu xie jin,qin qiang qi,cu chu tang,cheng"
  + " zhu hu gan yue qing,jing tuo,du jue qiao qin lu zun xi ju yuan lei yan,dan lin bo,bi cha,sa you ao mo,wen cu shang tian"
  + " yun lian piao,bi dan ji bin yi ren e gu ke lu zhi yi zhen hu li yao shi zhi quan lu zhe nian wang chuo zi cou lu lin we"
  + "i jian qiang jia,ga ji ji kan,zhen deng gai jian zang,cang ou ling bu,pou beng zeng pi pu ga,xu la gan,han hao tan,yu ga"
  + "o ze xin,xuan yun jiong,gui he,e zan mao yu chang ni,zhi qi,zhi cheng,sheng ye chao,zhao yan hui bu han gui xuan kui ai,"
  + "nuan ming tun xun yao xi nang ben,bi shi kuang yi zhi zi gai jin zhen lai qiu ji dan fu chan ji xi di yu gou jin qu jian"
  + " jiang pin mao gu wu gu ji,yi ju jian,qian pian kao qie,qi sa,suo bai ge bai,bo mao mu cui,qiao jian san shu,yu chang lu"
  + " pu qu pie dao xian chuan dong ya yin,yan ke yun pu chi,sou jiao,qiao du die you yuan guo yue wo rong,chen huang jing ru"
  + "an,wan tai gong zhun,chun na,nu yao qian,xu long dong ka lu jia shen,chen zhou zuo gua,gu zhen,zhun qu,xu zhi,chi jing g"
  + "uang dong yan kuai sa hai,gai pian zhen mi tun,dun luo cuo,qie pao wan,huan niao jing yan,a fei yu zong ding jian,qian c"
  + "ou nan mian wa e shu,yu cheng ying,sheng ge lv bin teng zhi chuai,zha gu meng,mang sao shan,dan lian lin,lian yu xi yi,q"
  + "i sha,xia xin she,xi biao sa ju sou biao biao shu gou,kou gu hu,que fei ji lan yu,wu pei mao,wu zhan jing ni liu yi yang"
  + " wei dun,tun qiang shi hu zhu xuan tai ye yang wu han men chao,zhuo yan,yi hu yu wei,yu duan bao xuan bian tui liu man s"
  + "hang yun,yu yi yu,ao fan,fen sui xian,bing jue,jiao cuan biao,huo dao,tao xu,xiu xi li hu jiong hu fei shi si xian zhi q"
  + "u hu fu,fei zuo mi,ni zhi ci,si zhen tiao qi chan,shan xi zhuo xi rang te,dao tan,keng dui jia,qi hui nv nen,ren yang zi"
  + " que qian min,fen te,ni qi dui mao men gang,zhuang yu yu da,ta xue miao ji gan,han dang huo,hua che dun ya zhuo,chuo bia"
  + "n feng fa,jie ai li long zha,zuo tong di,zhi la,li tuo fu,fei xing,keng mang xia qiao zhai dong,tong nao ge,luo wo,e qi "
  + "dui bei ding chen du,zhou jie,ke di xuan bian zhe gun sang qing qu dun deng jiang ca meng bo kan zhi,xian fu fu xu mian "
  + "kou dun,zhun miao dan,chen sheng yuan yi,chi sui,hui zi chi mou lai jian di,ti suo,jun ya ni sui,hui pi rui sou kui,ji m"
  + "ao,wu ke ming,meng piao cheng,zheng kan lin,lian gu ting,ding bi quan tian fan zhen she wan,yuan tuan fu gang gu li yan "
  + "pi lan,nan li ji zeng he,ke guan juan jin ga yi po zhao liao tu chuan shan men chai nv bu tai ju ban qian fang kang tou,"
  + "dou huo ba,pa yu zheng gu ke po bu bo yue mu tan dian,tian shuo shi xuan ta,tuo bi ni pi duo kao lao er you cheng jia na"
  + "o ye dang,cheng diao yin kai zhu ding,ting diu hua quan ha sha diao,yao zheng se chong tang an ru lao lai te keng zeng l"
  + "i gao e cuo lve liu kai jian lang qin ju a qiang nuo ben de ke kun gu huo pei juan tan,xian zi qie kai si e cha sou huan"
  + " ai lou qiang fei mei mo ge juan na liu yi jia bin biao tang man luo yong zu xuan di chan,tan jue pu lu dui,dun lan pu c"
  + "uan qiang deng huo zhuo yi cha biao zhong shen cuo zhi,kai bi zi mo shu lv ji,xi fu lang ke,hua ren zhen,bian ji,ze se n"
  + "ian fu,bi rang,reng gui jiao hao,hui xi po,pan die hu,huo yong,dong jiu yuan bao zhen gu dong lu qu chi si er zhi gua xi"
  + "u luan bo li gu,hu yu xian ti wu miao an bei chun hu e ci mei wu yao jian ying zhe liu liao jiao jiu yu hu lu guan ne di"
  + "ng,ne jie li shan li you gan ke,e dan,da zha pao zhu xuan jia ya yi zhi lao wu,pi cuo xian sha zhu fei gu wei yu yu dan "
  + "la yi hou chai,cuo lou jia,xia sao chi mo ban ji huang biao luo ying zhai,ji long yin chou,lu ban lai yi dian pi dian qu"
  + " yi song xi qiong,kong zhun,tun bian yao tiao dou ke yu,dou xun,yin ju yu yi cha na ren jin,qin mei,yi pan,fan dang jia,"
  + "qia ge,luo ken lian,shao cheng lian jian biao chu,zhe ti,xi bi,pi ju duo da bei bao lv bian,pian lan chi zhe,die qiang r"
  + "u pan pi,shu xu jun cun jin,qin lei zi chao si huo lao tang ou lou jiang nou mo die ding dan ling ning gua,guo kui ao,yo"
  + "u tan,qin han qi hang jie,xie he,ge ying ke han e zhuan nie man sang hao ru pin hu qian qiu ji chai hui ge meng fu pi ru"
  + "i xian hao,ci jie gong,zhong dou yin chi han gu he,ke li you,zhu ran,tian zha qiu ling cheng you,niu qiong,gong jia nao "
  + "zhi si qu ting,dian kuo,she qi jiao yang mou,mao shen zhe shao,xiao wu li chu,yu fu qiang qing,jing qi xi yu,guo fei,pei"
  + " guo,luo guo yi,xi pi,miao tiao,diao quan,juan wan lang meng chun rong nan fu kui ke fu sou yu you lou qiu,you bian,pian"
  + " mao,wu qin ao man mang,meng ma,mo yuan xi,ci chi tang pang,bang shi,zhe huang cao piao tang xi xiang zhong zhang shuai "
  + "mao,meng peng hui pan,fan shan huo,yue meng chan lian mie li,luo du qu,jue fou ying qing xia shi zhu,du yu ji du ji jian"
  + " zhao zi hu,wen qiong po da sheng ze,zuo gou li si tiao,shao jia bian chi kou bi xian yan quan zheng yun,jun shi gang pa"
  + " shao xiao qing,jing ze qie zhu,zhuo ruo,na qian tuo bi dan kong yuan,wan xiao zhen,jian kui huang hou gou fei li bi,pi "
  + "chi su mie dou lu duan gui dian zan deng bo lai zhou yu,yong yu chong,chuang xi,que nie nv chuan,xiang shan yi bi zhong "
  + "ban fang ge lu zhu,zhou ze xi shao wei meng shou cao chong,zhuang meng qin niao jia qiu sha bi di qiang suo,zui jie tang"
  + " xi xian mi ba li tiao xi zi,ci can lin zong san,shen hou zan ci xu rou qiu jiang gen,hen ji,jie yi ling xi zhu fei jian"
  + " pian he,li yi mi,si zhi qi qi,qing yao,you dao,du fu qu jiu ju,qie lie zi,ci zan nan zhe jiang shi,chi ding gan,hang zh"
  + "ou yi gu cu,zuo tuo,duo xian ming zhi yan shai,shi cheng tu lei kun pei hu ti xu hai tang lao bu jiao,qiao xi ju li xun "
  + "shi cuo dun qiong,qiang xue,chi cu bie bao,bo ta,sa jian,yan fu qiang zhi fu shan li,luo tuo jia bo,bi tai kui,xie qiao "
  + "bi xian,sun xian ji jiao,qiao liang,lang ji chuo,diao huai chi zhi dian bo,pou zhi jian die chuai,shuan zhong ju duo,chu"
  + "o cuo pian rou nie pan qi,xi chu jue,gui pu fan cu,zu zhu,zhuo lin chan,zhan lie zuan xie zhi,zhai diao mo,ma xiu mo pi "
  + "hu jue,kui shang gu zi,zui gong su zhi zi qing jing,liang yu,xu li wen ting ji pei fei sha yin ai xian,san mai,li chen j"
  + "u bao tiao zi ken,yin yu chuo wo min,mian yuan tuo zhui,cui sun juan,jun ju luo qu,ju chou qiong luan wu zan mou ao liu "
  + "bei xin,xun you fang ba,bo ping nian lu su fu hou tai gui,xie jie wei er ji jiao xiang xun geng li lian jian shi tiao gu"
  + "n sha huan ji qing,zheng ling zou fei kun chang gu ni nian diao shi zi fen die e qiu fu huang bian sao ao qi ta guan yao"
  + " le biao xue man min yong gui shan zun li da yang da qiao man,men jian ju,qu rou gou bei,fu jie,jia tou,gu ku gu,hu di h"
  + "ou ge ke,kua bi lou qia,ge kuan bin du mei ba yan liang xiao wang chi xiang yan tie tao yong biao,piao kun mao ran tiao "
  + "ji,jie zi xiu quan jiu bin huan lie mo,ma hui mi ji jun,qun zhu mi qi ao,biao she lin dai chu you,yi xia yi qu du li,lai"
  + " qing can an fen you wu yan xi qiu han zha mie shu yuan xi"
;
