/*
 * cryptanalysis2.js — 密码分析扩展（T97，cat:'analysis'）。
 *
 * 定位：与 T57 cryptanalysis.js（freqAnalysis/icAnalysis/kasiskiTest/...）正交——
 * 本文件做「自动化恢复」：给密文直接还原密钥 / 明文。不碰 cryptanalysis.js。
 *
 * 覆盖：
 * vigenereAuto 维吉尼亚全自动破解（IC 估阶 + 列卡方恢复密钥 + 解密）
 * hillKnownPlain Hill 已知明文攻击（C·P⁻¹ mod 26 还原密钥矩阵）
 * playfairCrack Playfair 爬山破解（模拟退火 + 四元组适应度）
 *
 * 解密一致性：从 classic.js import vigenereDecode / playfairDecode / parseHillKey /
 * invertMatrixMod，保证恢复结果与项目加密器严丝合缝。
 *
 * 红线：只新建本文件；op id 不与 analysis 现有 op（freqAnalysis/icAnalysis/kasiskiTest/
 * chiSquareAnalysis/subCipherSolver/caesarBrute）冲突。
 */
import { register } from "./registry.js";
import {
  vigenereDecode, playfairDecode, parseHillKey, invertMatrixMod,
} from "./classic.js";

const AZ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const AZ_NO_J = "ABCDEFGHIKLMNOPQRSTUVWXYZ";

// 英文字母频率（A-Z，百分比，用于 Vigenère 卡方）
const ENG_FREQ = [
  8.167, 1.492, 2.782, 4.253, 12.702, 2.228, 2.015, 6.094, 6.966, 0.153,
  0.772, 4.025, 2.406, 6.749, 7.507, 1.929, 0.095, 5.987, 6.327, 9.056,
  2.758, 0.978, 2.360, 0.150, 1.974, 0.074,
];

// ============================================================
// 通用工具
// ============================================================
function cleanLetters(text) {
  return (text || "").toUpperCase().replace(/[^A-Z]/g, "");
}

// mulberry32 — 确定性 PRNG（爬山可复现）
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ============================================================
// Vigenère 全自动
// ============================================================

// 重合指数 IC = Σ f_i(f_i-1) / (N(N-1))
function indexCoincidence(text) {
  const n = text.length;
  if (n < 2) return 0;
  const counts = new Array(26).fill(0);
  for (const ch of text) counts[ch.charCodeAt(0) - 65]++;
  let sum = 0;
  for (const c of counts) sum += c * (c - 1);
  return sum / (n * (n - 1));
}

// 估阶：取平均 IC 最高的长度（真周期及其倍数会峰起），再用 0.9×max 阈值归约到最小周期
function guessKeyLength(ct, maxLen = 20) {
  const scores = [];
  for (let L = 1; L <= maxLen; L++) {
    const cols = [];
    for (let i = 0; i < L; i++) {
      let col = "";
      for (let j = i; j < ct.length; j += L) col += ct[j];
      cols.push(col);
    }
    const avg = cols.reduce((s, c) => s + indexCoincidence(c), 0) / L;
    scores.push({ L, avg });
  }
  let maxAvg = 0;
  for (const s of scores) if (s.avg > maxAvg) maxAvg = s.avg;
 // 候选：avgIC >= 0.9×max 且 L>=2（L=1 是整文 IC，无周期意义），取最小者
  const candidates = scores.filter((s) => s.L >= 2 && s.avg >= 0.9 * maxAvg);
  if (candidates.length === 0) {
    const best = scores.reduce((a, b) => (a.avg > b.avg ? a : b));
    return best;
  }
  candidates.sort((a, b) => a.L - b.L);
  return candidates[0];
}

// 单列卡方：返回最佳移位 0..25
function bestShift(col) {
  const n = col.length;
  const counts = new Array(26).fill(0);
  for (const ch of col) counts[ch.charCodeAt(0) - 65]++;
  let bestS = 0, bestChi = Infinity;
  for (let s = 0; s < 26; s++) {
    let chi = 0;
    for (let i = 0; i < 26; i++) {
      const observed = counts[(i + s) % 26];
      const expected = (ENG_FREQ[i] / 100) * n;
      const d = observed - expected;
      chi += (d * d) / (expected || 0.01);
    }
    if (chi < bestChi) { bestChi = chi; bestS = s; }
  }
  return bestS;
}

function recoverVigenereKey(ct, keyLen) {
  let key = "";
  for (let i = 0; i < keyLen; i++) {
    let col = "";
    for (let j = i; j < ct.length; j += keyLen) col += ct[j];
    key += AZ[bestShift(col)];
  }
  return key;
}

function vigenereAuto(text, p = {}) {
  const maxLen = Math.min(Number(p && p.maxKeyLen) || 20, 30);
  const ct = cleanLetters(text);
  const lines = [];
  lines.push("=== 维吉尼亚全自动破解 ===");
  lines.push(`密文长度：${ct.length}（仅字母）`);
  if (ct.length < 20) {
    lines.push("（密文过短，统计不可靠，结果仅供参考）");
  }
  lines.push("");
  const est = guessKeyLength(ct, maxLen);
  const target = 0.0667;
  const all = [];
  for (let L = 1; L <= Math.min(maxLen, 12); L++) {
    const cols = [];
    for (let i = 0; i < L; i++) {
      let col = "";
      for (let j = i; j < ct.length; j += L) col += ct[j];
      cols.push(col);
    }
    const avg = cols.reduce((s, c) => s + indexCoincidence(c), 0) / L;
    all.push({ L, avg });
  }
  lines.push("--- 各密钥长度平均 IC（接近 0.0667 为英语）---");
  for (const a of all) {
    lines.push(`  L=${String(a.L).padStart(2)}  IC=${a.avg.toFixed(4)}${a.L === est.L ? "  ← 选中" : ""}`);
  }
  lines.push("");
  const key = recoverVigenereKey(ct, est.L);
  const plain = vigenereDecode(ct, key);
  lines.push(`推断密钥长度：${est.L}`);
  lines.push(`恢复密钥：${key}`);
  lines.push("");
  lines.push("--- 解密结果 ---");
  lines.push(plain);
  return lines.join("\n");
}

// ============================================================
// Hill 已知明文攻击
// ============================================================

function matMulMod(A, B, m) {
  const n = A.length;
  const C = Array.from({ length: n }, () => new Array(n).fill(0));
  for (let i = 0; i < n; i++)
    for (let j = 0; j < n; j++) {
      let s = 0;
      for (let k = 0; k < n; k++) s += A[i][k] * B[k][j];
      C[i][j] = ((s % m) + m) % m;
    }
  return C;
}

// 取前 n² 字母，按「每块为列」构造 n×n 矩阵：mat[r][block] = 第 block 块第 r 字母
function lettersToColumnMatrix(text, n) {
  const s = cleanLetters(text);
  if (s.length < n * n) throw new Error(`需要至少 ${n * n} 个字母明文/密文`);
  const mat = Array.from({ length: n }, () => new Array(n).fill(0));
  for (let block = 0; block < n; block++) {
    for (let r = 0; r < n; r++) {
      mat[r][block] = s.charCodeAt(block * n + r) - 65;
    }
  }
  return mat;
}

function hillKnownPlain(text, p = {}) {
  const plain = text;
  const cipher = (p && p.cipher) || "";
  const n = Math.max(2, Math.min(Number(p && p.size) || 2, 4));
  const lines = [];
  lines.push(`=== Hill 已知明文攻击 (${n}×${n}) ===`);
  lines.push("");
  const P = lettersToColumnMatrix(plain, n);
  const C = lettersToColumnMatrix(cipher, n);
  let K;
  try {
    const Pinv = invertMatrixMod(P, 26);
    K = matMulMod(C, Pinv, 26);
  } catch (e) {
    lines.push("✗ 明文矩阵在 mod 26 下不可逆，换一组已知明文（使其行列式与 26 互质）");
    return lines.join("\n");
  }
  const keyNums = [];
  for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) keyNums.push(K[i][j]);
  const keyStr = keyNums.map((x) => AZ[x]).join("");
  const keyNumStr = keyNums.join(" ");
  lines.push("恢复的密钥矩阵 K（C = K·P mod 26）：");
  for (let i = 0; i < n; i++) {
    lines.push("  " + K[i].map((x) => String(x).padStart(2)).join(" "));
  }
  lines.push("");
  lines.push(`密钥（字母）：${keyStr}`);
  lines.push(`密钥（数字）：${keyNumStr}`);
  lines.push("");
  lines.push("--- 验证 ---");
  const sP = cleanLetters(plain).slice(0, n * n);
  const sC = cleanLetters(cipher).slice(0, n * n);
  let verify = "";
  const pNums = sP.split("").map((c) => c.charCodeAt(0) - 65);
  for (let i = 0; i < n * n; i += n) {
    const vec = pNums.slice(i, i + n);
    for (let r = 0; r < n; r++) {
      let sum = 0;
      for (let c = 0; c < n; c++) sum += K[r][c] * vec[c];
      verify += AZ[((sum % 26) + 26) % 26];
    }
  }
  const ok = verify === sC;
  lines.push(`K·P(前 ${n * n} 字母) = ${verify}`);
  lines.push(`密文前 ${n * n} 字母  = ${sC}`);
  lines.push(ok ? "✓ 验证通过：恢复的密钥正确" : "✗ 验证不一致（明文/密文配对或阶数有误）");
  return lines.join("\n");
}

// ============================================================
// Playfair 爬山破解（模拟退火 + 四元组适应度）
// ============================================================

// 语料：8 部公有领域名著均匀取样（Gutenberg：Pride & Prejudice / Alice / Sherlock Holmes /
// Moby Dick / Tom Sawyer / Frankenstein / Metamorphosis / Huckleberry Finn），仅 A-Z 与空格。
// 通用单表替换求解对语料规模敏感：样例语料过小会让错解适应度高于真文而卡死实测）。
const CORPUS = (
  "ILLUSTRATION GEORGE ALLEN PUBLISHER CHARING CROSS ROAD LONDON RUSKIN HOUSE ILLUSTRATION READING JANE S LETTERS CHAP PRIDE AND PREJUDICE BY JANE AUSTEN WITH A PREFACE BY GEORGE SAINTSBURY AND ILLUSTRATIONS BY HUGH THOMSON ILLUSTRATION RUSKIN CHARING HOUSE CROSS ROAD LONDON GEORGE ALLEN CHISWICK PRESS CHARLES WHITTINGHAM AND CO TOOKS COURT CHANCERY LANE LONDON ILLUSTRATION TO J COMYNS CARR IN ACKNOWLEDGMENT OF ALL I OWE TO HIS FRIENDSHIP AND ADVICE THESE ILLUSTRATIONS ARE GRATEFULLY INSCRIBED HUGH THOMSON PREFACE ILLUSTRATION WALT WHITMAN HAS SOMEWHERE A FINE AND JUST DISTINCTION BETWEEN LOVING BY ALLOWANCE AND LOVING WITH PERSONAL LOVE THIS DISTINCTION APPLIES TO BOOKS AS WELL AS TO MEN AND WOMEN AND IN THE CASE OF THE NOT VERY NUMEROUS AUTHORS WHO ARE THE OBJECTS OF THE PERSONAL AFFECTION IT BRINGS A CURIOUS CONSEQUENCE WITH IT THERE IS MUCH MORE DIFFERENCE AS TO THEIR BEST WORK THAN IN THE CASE OF THOSE OTHERS WHO ARE LOVED BY ALLOWANCE BY CONVENTION AND BECAUSE IT IS FELT TO BE THE R " +
  "IGHT AND PROPER THING TO LOVE THEM AND IN THE SECT FAIRLY LARGE AND YET UNUSUALLY CHOICE OF AUSTENIANS OR JANITES THERE WOULD PROBABLY BE FOUND PARTISANS OF THE CLAIM TO PRIMACY OF ALMOST EVERY ONE OF THE NOVELS TO SOME THE DELIGHTFUL FRESHNESS AND HUMOUR OF NORTHANGER ABBEY ITS COMPLETENESS FINISH AND ENTRAIN OBSCURE THE UNDOUBTED CRITICAL FACTS THAT ITS SCALE IS SMALL AND ITS SCHEME AFTER ALL THAT OF BURLESQUE OR PARODY A KIND IN WHICH THE FIRST RANK IS REACHED WITH DIFFICULTY PERSUASION RELATIVELY FAINT IN TONE AND NOT ENTHRALLING IN INTEREST HAS DEVOTEES WHO EXALT ABOVE ALL THE OTHERS ITS EXQUISITE DELICACY AND KEEPING THE CATASTROPHE OF MANSFIELD PARK IS ADMITTEDLY THEATRICAL THE HERO AND HEROINE ARE INSIPID AND THE AUTHOR HAS ALMOST WICKEDLY DESTROYED ALL ROMANTIC INTEREST BY EXPRESSLY ADMITTING THAT EDMUND ONLY TOOK FANNY BECAUSE MARY SHOCKED HIM AND THAT FANNY MIGHT VERY LIKELY HAVE TAKEN CRAWFORD IF HE HAD BEEN A LITTLE MORE ASSIDUOUS YET THE MATCHLESS REHEARSAL SCENES AND THE " +
  " CHARACTERS OF MRS NORRIS AND OTHERS HAVE SECURED I BELIEVE A CONSIDERABLE PARTY FOR IT SENSE AND SENSIBILITY HAS PERHAPS THE FEWEST OUT AND OUT ADMIRERS BUT IT DOES NOT WANT THEM I SUPPOSE HOWEVER THAT THE MAJORITY OF AT LEAST COMPETENT VOTES WOULD ALL THINGS CONSIDERED BE DIVIDED BETWEEN EMMA AND THE PRESENT BOOK AND PERHAPS THE VULGAR VERDICT IF INDEED A FONDNESS FOR MISS AUSTEN BE NOT OF ITSELF A PATENT OF EXEMPTION FROM ANY POSSIBLE CHARGE OF VULGARITY WOULD GO FOR EMMA IT IS THE LARGER THE MORE VARIED THE MORE POPULAR THE AUTHOR HAD BY THE TIME OF ITS COMPOSITION SEEN RATHER MORE OF THE WORLD AND HAD IMPROVED HER GENERAL THOUGH NOT HER MOST PECULIAR AND CHARACTERISTIC DIALOGUE SUCH FIGURES AS MISS BATES AS THE ELTONS CANNOT BUT UNITE THE SUFFRAGES OF EVERYBODY ON THE OTHER HAND I FOR MY PART DECLARE FOR PRIDE AND PREJUDICE UNHESITATINGLY IT SEEMS TO ME THE MOST PERFECT THE MOST CHARACTERISTIC THE MOST EMINENTLY QUINTESSENTIAL OF ITS AUTHOR S WORKS AND FOR THIS CONTENTION IN SUCH  " +
  "NARROW SPACE AS IS PERMITTED TO ME I PROPOSE HERE TO SHOW CAUSE IN THE FIRST PLACE THE BOOK IT MAY BE BARELY NECESSARY TO REMIND THE READER WAS IN ITS FIRST SHAPE WRITTEN VERY EARLY SOMEWHERE ABOUT WHEN MISS AUSTEN WAS BARELY TWENTY ONE THOUGH IT WAS REVISED AND FINISHED AT CHAWTON SOME FIFTEEN YEARS LATER AND WAS NOT PUBLISHED TILL ONLY FOUR YEARS BEFORE HER DEATH I DO NOT KNOW WHETHER IN THIS COMBINATION OF THE FRESH AND VIGOROUS PROJECTION OF YOUTH AND THE CRITICAL REVISION OF MIDDLE LIFE THERE MAY BE TRACED THE DISTINCT SUPERIORITY IN POINT OF CONSTRUCTION WHICH AS IT SEEMS TO ME IT POSSESSES OVER ALL THE OTHERS THE PLOT THOUGH NOT ELABORATE IS ALMOST REGULAR ENOUGH FOR FIELDING HARDLY A CHARACTER HARDLY AN INCIDENT COULD BE RETRENCHED WITHOUT LOSS TO THE STORY THE ELOPEMENT OF LYDIA AND WICKHAM IS NOT LIKE THAT OF CRAWFORD AND MRS RUSHWORTH A COUP DE TH TRE IT CONNECTS ITSELF IN THE STRICTEST WAY WITH THE COURSE OF THE STORY EARLIER AND BRINGS ABOUT THE DENOUEMENT WITH COMPLETE PR " +
  "OPRIETY ALL THE MINOR PASSAGES THE LOVES OF JANE AND BINGLEY THE ADVENT OF MR COLLINS THE VISIT TO HUNSFORD THE DERBYSHIRE TOUR FIT IN AFTER THE SAME UNOSTENTATIOUS BUT MASTERLY FASHION THERE IS NO ATTEMPT AT THE HIDE AND SEEK IN AND OUT BUSINESS WHICH IN THE TRANSACTIONS BETWEEN FRANK CHURCHILL AND JANE FAIRFAX CONTRIBUTES NO DOUBT A GOOD DEAL TO THE INTRIGUE OF EMMA BUT CONTRIBUTES IT IN A FASHION WHICH I DO NOT THINK THE BEST FEATURE OF THAT OTHERWISE ADMIRABLE BOOK ALTHOUGH MISS AUSTEN ALWAY ILLUSTRATION ALICE S ADVENTURES IN WONDERLAND BY LEWIS CARROLL THE MILLENNIUM FULCRUM EDITION CONTENTS CHAPTER I DOWN THE RABBIT HOLE CHAPTER II THE POOL OF TEARS CHAPTER III A CAUCUS RACE AND A LONG TALE CHAPTER IV THE RABBIT SENDS IN A LITTLE BILL CHAPTER V ADVICE FROM A CATERPILLAR CHAPTER VI PIG AND PEPPER CHAPTER VII A MAD TEA PARTY CHAPTER VIII THE QUEEN S CROQUET GROUND CHAPTER IX THE MOCK TURTLE S STORY CHAPTER X THE LOBSTER QUADRILLE CHAPTER XI WHO STOLE THE TARTS CHAPTER XII ALICE S E " +
  "VIDENCE CHAPTER I DOWN THE RABBIT HOLE ALICE WAS BEGINNING TO GET VERY TIRED OF SITTING BY HER SISTER ON THE BANK AND OF HAVING NOTHING TO DO ONCE OR TWICE SHE HAD PEEPED INTO THE BOOK HER SISTER WAS READING BUT IT HAD NO PICTURES OR CONVERSATIONS IN IT AND WHAT IS THE USE OF A BOOK THOUGHT ALICE WITHOUT PICTURES OR CONVERSATIONS SO SHE WAS CONSIDERING IN HER OWN MIND AS WELL AS SHE COULD FOR THE HOT DAY MADE HER FEEL VERY SLEEPY AND STUPID WHETHER THE PLEASURE OF MAKING A DAISY CHAIN WOULD BE WORTH THE TROUBLE OF GETTING UP AND PICKING THE DAISIES WHEN SUDDENLY A WHITE RABBIT WITH PINK EYES RAN CLOSE BY HER THERE WAS NOTHING SO VERY REMARKABLE IN THAT NOR DID ALICE THINK IT SO VERY MUCH OUT OF THE WAY TO HEAR THE RABBIT SAY TO ITSELF OH DEAR OH DEAR I SHALL BE LATE WHEN SHE THOUGHT IT OVER AFTERWARDS IT OCCURRED TO HER THAT SHE OUGHT TO HAVE WONDERED AT THIS BUT AT THE TIME IT ALL SEEMED QUITE NATURAL BUT WHEN THE RABBIT ACTUALLY TOOK A WATCH OUT OF ITS WAISTCOAT POCKET AND LOOKED AT  " +
  "IT AND THEN HURRIED ON ALICE STARTED TO HER FEET FOR IT FLASHED ACROSS HER MIND THAT SHE HAD NEVER BEFORE SEEN A RABBIT WITH EITHER A WAISTCOAT POCKET OR A WATCH TO TAKE OUT OF IT AND BURNING WITH CURIOSITY SHE RAN ACROSS THE FIELD AFTER IT AND FORTUNATELY WAS JUST IN TIME TO SEE IT POP DOWN A LARGE RABBIT HOLE UNDER THE HEDGE IN ANOTHER MOMENT DOWN WENT ALICE AFTER IT NEVER ONCE CONSIDERING HOW IN THE WORLD SHE WAS TO GET OUT AGAIN THE RABBIT HOLE WENT STRAIGHT ON LIKE A TUNNEL FOR SOME WAY AND THEN DIPPED SUDDENLY DOWN SO SUDDENLY THAT ALICE HAD NOT A MOMENT TO THINK ABOUT STOPPING HERSELF BEFORE SHE FOUND HERSELF FALLING DOWN A VERY DEEP WELL EITHER THE WELL WAS VERY DEEP OR SHE FELL VERY SLOWLY FOR SHE HAD PLENTY OF TIME AS SHE WENT DOWN TO LOOK ABOUT HER AND TO WONDER WHAT WAS GOING TO HAPPEN NEXT FIRST SHE TRIED TO LOOK DOWN AND MAKE OUT WHAT SHE WAS COMING TO BUT IT WAS TOO DARK TO SEE ANYTHING THEN SHE LOOKED AT THE SIDES OF THE WELL AND NOTICED THAT THEY WERE FILLED WITH CUPBO " +
  "ARDS AND BOOK SHELVES HERE AND THERE SHE SAW MAPS AND PICTURES HUNG UPON PEGS SHE TOOK DOWN A JAR FROM ONE OF THE SHELVES AS SHE PASSED IT WAS LABELLED ORANGE MARMALADE BUT TO HER GREAT DISAPPOINTMENT IT WAS EMPTY SHE DID NOT LIKE TO DROP THE JAR FOR FEAR OF KILLING SOMEBODY UNDERNEATH SO MANAGED TO PUT IT INTO ONE OF THE CUPBOARDS AS SHE FELL PAST IT WELL THOUGHT ALICE TO HERSELF AFTER SUCH A FALL AS THIS I SHALL THINK NOTHING OF TUMBLING DOWN STAIRS HOW BRAVE THEY LL ALL THINK ME AT HOME WHY I WOULDN T SAY ANYTHING ABOUT IT EVEN IF I FELL OFF THE TOP OF THE HOUSE WHICH WAS VERY LIKELY TRUE DOWN DOWN DOWN WOULD THE FALL NEVER COME TO AN END I WONDER HOW MANY MILES I VE FALLEN BY THIS TIME SHE SAID ALOUD I MUST BE GETTING SOMEWHERE NEAR THE CENTRE OF THE EARTH LET ME SEE THAT WOULD BE FOUR THOUSAND MILES DOWN I THINK FOR YOU SEE ALICE HAD LEARNT SEVERAL THINGS OF THIS SORT IN HER LESSONS IN THE SCHOOLROOM AND THOUGH THIS WAS NOT A VERY GOOD OPPORTUNITY FOR SHOWING OFF HER KNOWLEDGE AS  " +
  "THERE WAS NO ONE TO LISTEN TO HER STILL IT WAS GOOD PRACTICE TO SAY IT OVER YES THAT S ABOUT THE RIGHT DISTANCE BUT THEN I WONDER WHAT LATITUDE OR LONGITUDE I VE GOT TO ALICE HAD NO IDEA WHAT LATITUDE WAS OR LONGITUDE EITHER BUT THOUGHT THEY WERE NICE GRAND WORDS TO SAY PRESENTLY SHE BEGAN AGAIN I WONDER IF I SHALL FALL RIGHT THROUGH THE EARTH HOW FUNNY IT LL SEEM TO COME OUT AMONG THE PEOPLE THAT WALK WITH THEIR HEADS DOWNWARD THE ANTIPATHIES I THINK SHE WAS RATHER GLAD THERE WAS NO ONE LISTENING THIS TIME AS IT DIDN T SOUND AT ALL THE RIGHT WORD BUT I SHALL HAVE TO ASK THEM WHAT THE NAME OF THE COUNTRY IS YOU KNOW PLEASE MA AM IS THIS NEW ZEALAND OR AUSTRALIA AND SHE TRIED TO CURTSEY AS SHE SPOKE FANCY CURTSEYING AS YOU RE FALLING THROUGH THE AIR DO YOU THINK YOU COULD MANAGE IT AND WHAT AN IGNORANT LITTLE GIRL SHE LL THINK ME FOR ASKING NO IT LL NEVER DO TO ASK PERHAPS I SHALL SEE IT WRITTEN UP SOMEWHERE DOWN DOWN DOWN THERE WAS NOTHING ELSE TO DO SO ALICE SOON BEGAN TALKING AGAIN D " +
  "I THE ADVENTURES OF SHERLOCK HOLMES BY ARTHUR CONAN DOYLE CONTENTS I A SCANDAL IN BOHEMIA II THE RED HEADED LEAGUE III A CASE OF IDENTITY IV THE BOSCOMBE VALLEY MYSTERY V THE FIVE ORANGE PIPS VI THE MAN WITH THE TWISTED LIP VII THE ADVENTURE OF THE BLUE CARBUNCLE VIII THE ADVENTURE OF THE SPECKLED BAND IX THE ADVENTURE OF THE ENGINEER S THUMB X THE ADVENTURE OF THE NOBLE BACHELOR XI THE ADVENTURE OF THE BERYL CORONET XII THE ADVENTURE OF THE COPPER BEECHES I A SCANDAL IN BOHEMIA I TO SHERLOCK HOLMES SHE IS ALWAYS THE WOMAN I HAVE SELDOM HEARD HIM MENTION HER UNDER ANY OTHER NAME IN HIS EYES SHE ECLIPSES AND PREDOMINATES THE WHOLE OF HER SEX IT WAS NOT THAT HE FELT ANY EMOTION AKIN TO LOVE FOR IRENE ADLER ALL EMOTIONS AND THAT ONE PARTICULARLY WERE ABHORRENT TO HIS COLD PRECISE BUT ADMIRABLY BALANCED MIND HE WAS I TAKE IT THE MOST PERFECT REASONING AND OBSERVING MACHINE THAT THE WORLD HAS SEEN BUT AS A LOVER HE WOULD HAVE PLACED HIMSELF IN A FALSE POSITION HE NEVER SPOKE OF THE SOFTER P " +
  "ASSIONS SAVE WITH A GIBE AND A SNEER THEY WERE ADMIRABLE THINGS FOR THE OBSERVER EXCELLENT FOR DRAWING THE VEIL FROM MEN S MOTIVES AND ACTIONS BUT FOR THE TRAINED REASONER TO ADMIT SUCH INTRUSIONS INTO HIS OWN DELICATE AND FINELY ADJUSTED TEMPERAMENT WAS TO INTRODUCE A DISTRACTING FACTOR WHICH MIGHT THROW A DOUBT UPON ALL HIS MENTAL RESULTS GRIT IN A SENSITIVE INSTRUMENT OR A CRACK IN ONE OF HIS OWN HIGH POWER LENSES WOULD NOT BE MORE DISTURBING THAN A STRONG EMOTION IN A NATURE SUCH AS HIS AND YET THERE WAS BUT ONE WOMAN TO HIM AND THAT WOMAN WAS THE LATE IRENE ADLER OF DUBIOUS AND QUESTIONABLE MEMORY I HAD SEEN LITTLE OF HOLMES LATELY MY MARRIAGE HAD DRIFTED US AWAY FROM EACH OTHER MY OWN COMPLETE HAPPINESS AND THE HOME CENTRED INTERESTS WHICH RISE UP AROUND THE MAN WHO FIRST FINDS HIMSELF MASTER OF HIS OWN ESTABLISHMENT WERE SUFFICIENT TO ABSORB ALL MY ATTENTION WHILE HOLMES WHO LOATHED EVERY FORM OF SOCIETY WITH HIS WHOLE BOHEMIAN SOUL REMAINED IN OUR LODGINGS IN BAKER STREET BURIE " +
  "D AMONG HIS OLD BOOKS AND ALTERNATING FROM WEEK TO WEEK BETWEEN COCAINE AND AMBITION THE DROWSINESS OF THE DRUG AND THE FIERCE ENERGY OF HIS OWN KEEN NATURE HE WAS STILL AS EVER DEEPLY ATTRACTED BY THE STUDY OF CRIME AND OCCUPIED HIS IMMENSE FACULTIES AND EXTRAORDINARY POWERS OF OBSERVATION IN FOLLOWING OUT THOSE CLUES AND CLEARING UP THOSE MYSTERIES WHICH HAD BEEN ABANDONED AS HOPELESS BY THE OFFICIAL POLICE FROM TIME TO TIME I HEARD SOME VAGUE ACCOUNT OF HIS DOINGS OF HIS SUMMONS TO ODESSA IN THE CASE OF THE TREPOFF MURDER OF HIS CLEARING UP OF THE SINGULAR TRAGEDY OF THE ATKINSON BROTHERS AT TRINCOMALEE AND FINALLY OF THE MISSION WHICH HE HAD ACCOMPLISHED SO DELICATELY AND SUCCESSFULLY FOR THE REIGNING FAMILY OF HOLLAND BEYOND THESE SIGNS OF HIS ACTIVITY HOWEVER WHICH I MERELY SHARED WITH ALL THE READERS OF THE DAILY PRESS I KNEW LITTLE OF MY FORMER FRIEND AND COMPANION ONE NIGHT IT WAS ON THE TWENTIETH OF MARCH I WAS RETURNING FROM A JOURNEY TO A PATIENT FOR I HAD NOW RETURNED TO C " +
  "IVIL PRACTICE WHEN MY WAY LED ME THROUGH BAKER STREET AS I PASSED THE WELL REMEMBERED DOOR WHICH MUST ALWAYS BE ASSOCIATED IN MY MIND WITH MY WOOING AND WITH THE DARK INCIDENTS OF THE STUDY IN SCARLET I WAS SEIZED WITH A KEEN DESIRE TO SEE HOLMES AGAIN AND TO KNOW HOW HE WAS EMPLOYING HIS EXTRAORDINARY POWERS HIS ROOMS WERE BRILLIANTLY LIT AND EVEN AS I LOOKED UP I SAW HIS TALL SPARE FIGURE PASS TWICE IN A DARK SILHOUETTE AGAINST THE BLIND HE WAS PACING THE ROOM SWIFTLY EAGERLY WITH HIS HEAD SUNK UPON HIS CHEST AND HIS HANDS CLASPED BEHIND HIM TO ME WHO KNEW HIS EVERY MOOD AND HABIT HIS ATTITUDE AND MANNER TOLD THEIR OWN STORY HE WAS AT WORK AGAIN HE HAD RISEN OUT OF HIS DRUG CREATED DREAMS AND WAS HOT UPON THE SCENT OF SOME NEW PROBLEM I RANG THE BELL AND WAS SHOWN UP TO THE CHAMBER WHICH HAD FORMERLY BEEN IN PART MY OWN HIS MANNER WAS NOT EFFUSIVE IT SELDOM WAS BUT HE WAS GLAD I THINK TO SEE ME WITH HARDLY A WORD SPOKEN BUT WITH A KINDLY EYE HE WAVED ME TO AN ARMCHAIR THREW ACROSS HI " +
  "S CASE OF CIGARS AND INDICATED A SPIRIT CASE AND A GASOGENE IN THE CORNER THEN HE STOOD BEFORE THE FIRE AND LOOKED ME OVER IN HIS SINGULAR INTROSPECTIVE FASHION WEDLOCK SUITS YOU HE REMARKED I THINK WATSON THAT YOU HAVE PUT ON SEVEN AND A HALF POUNDS SINCE I SAW YOU SEVEN I ANSWERED INDEED I SHOULD HAVE THOUGHT A LITTLE MORE JUST A TRIFLE MORE I FANCY WATSON AND IN PRACTICE AGAIN I OBSERVE YOU DID NOT TELL ME THAT YOU INTENDED TO GO INTO HARNESS THEN HOW DO YOU KNOW I SEE IT I DEDUCE IT HOW DO I K MOBY DICK OR THE WHALE BY HERMAN MELVILLE CONTENTS ETYMOLOGY EXTRACTS SUPPLIED BY A SUB SUB LIBRARIAN CHAPTER LOOMINGS CHAPTER THE CARPET BAG CHAPTER THE SPOUTER INN CHAPTER THE COUNTERPANE CHAPTER BREAKFAST CHAPTER THE STREET CHAPTER THE CHAPEL CHAPTER THE PULPIT CHAPTER THE SERMON CHAPTER A BOSOM FRIEND CHAPTER NIGHTGOWN CHAPTER BIOGRAPHICAL CHAPTER WHEELBARROW CHAPTER NANTUCKET CHAPTER CHOWDER CHAPTER THE SHIP CHAPTER THE RAMADAN CHAPTER HIS MARK CHAPTER THE PROPHET CHAPTER ALL ASTIR CHAPT " +
  "ER GOING ABOARD CHAPTER MERRY CHRISTMAS CHAPTER THE LEE SHORE CHAPTER THE ADVOCATE CHAPTER POSTSCRIPT CHAPTER KNIGHTS AND SQUIRES CHAPTER KNIGHTS AND SQUIRES CHAPTER AHAB CHAPTER ENTER AHAB TO HIM STUBB CHAPTER THE PIPE CHAPTER QUEEN MAB CHAPTER CETOLOGY CHAPTER THE SPECKSNYDER CHAPTER THE CABIN TABLE CHAPTER THE MAST HEAD CHAPTER THE QUARTER DECK CHAPTER SUNSET CHAPTER DUSK CHAPTER FIRST NIGHT WATCH CHAPTER MIDNIGHT FORECASTLE CHAPTER MOBY DICK CHAPTER THE WHITENESS OF THE WHALE CHAPTER HARK CHAPTER THE CHART CHAPTER THE AFFIDAVIT CHAPTER SURMISES CHAPTER THE MAT MAKER CHAPTER THE FIRST LOWERING CHAPTER THE HYENA CHAPTER AHAB S BOAT AND CREW FEDALLAH CHAPTER THE SPIRIT SPOUT CHAPTER THE ALBATROSS CHAPTER THE GAM CHAPTER THE TOWN HO S STORY CHAPTER OF THE MONSTROUS PICTURES OF WHALES CHAPTER OF THE LESS ERRONEOUS PICTURES OF WHALES AND THE TRUE PICTURES OF WHALING SCENES CHAPTER OF WHALES IN PAINT IN TEETH IN WOOD IN SHEET IRON IN STONE IN MOUNTAINS IN STARS CHAPTER BRIT CHAPTER SQUID  " +
  "CHAPTER THE LINE CHAPTER STUBB KILLS A WHALE CHAPTER THE DART CHAPTER THE CROTCH CHAPTER STUBB S SUPPER CHAPTER THE WHALE AS A DISH CHAPTER THE SHARK MASSACRE CHAPTER CUTTING IN CHAPTER THE BLANKET CHAPTER THE FUNERAL CHAPTER THE SPHYNX CHAPTER THE JEROBOAM S STORY CHAPTER THE MONKEY ROPE CHAPTER STUBB AND FLASK KILL A RIGHT WHALE AND THEN HAVE A TALK OVER HIM CHAPTER THE SPERM WHALE S HEAD CONTRASTED VIEW CHAPTER THE RIGHT WHALE S HEAD CONTRASTED VIEW CHAPTER THE BATTERING RAM CHAPTER THE GREAT HEIDELBURGH TUN CHAPTER CISTERN AND BUCKETS CHAPTER THE PRAIRIE CHAPTER THE NUT CHAPTER THE PEQUOD MEETS THE VIRGIN CHAPTER THE HONOR AND GLORY OF WHALING CHAPTER JONAH HISTORICALLY REGARDED CHAPTER PITCHPOLING CHAPTER THE FOUNTAIN CHAPTER THE TAIL CHAPTER THE GRAND ARMADA CHAPTER SCHOOLS AND SCHOOLMASTERS CHAPTER FAST FISH AND LOOSE FISH CHAPTER HEADS OR TAILS CHAPTER THE PEQUOD MEETS THE ROSE BUD CHAPTER AMBERGRIS CHAPTER THE CASTAWAY CHAPTER A SQUEEZE OF THE HAND CHAPTER THE CASSOCK CHAPTER  " +
  "THE TRY WORKS CHAPTER THE LAMP CHAPTER STOWING DOWN AND CLEARING UP CHAPTER THE DOUBLOON CHAPTER LEG AND ARM CHAPTER THE DECANTER CHAPTER A BOWER IN THE ARSACIDES CHAPTER MEASUREMENT OF THE WHALE S SKELETON CHAPTER THE FOSSIL WHALE CHAPTER DOES THE WHALE S MAGNITUDE DIMINISH WILL HE PERISH CHAPTER AHAB S LEG CHAPTER THE CARPENTER CHAPTER AHAB AND THE CARPENTER CHAPTER AHAB AND STARBUCK IN THE CABIN CHAPTER QUEEQUEG IN HIS COFFIN CHAPTER THE PACIFIC CHAPTER THE BLACKSMITH CHAPTER THE FORGE CHAPTER THE GILDER CHAPTER THE PEQUOD MEETS THE BACHELOR CHAPTER THE DYING WHALE CHAPTER THE WHALE WATCH CHAPTER THE QUADRANT CHAPTER THE CANDLES CHAPTER THE DECK TOWARDS THE END OF THE FIRST NIGHT WATCH CHAPTER MIDNIGHT THE FORECASTLE BULWARKS CHAPTER MIDNIGHT ALOFT THUNDER AND LIGHTNING CHAPTER THE MUSKET CHAPTER THE NEEDLE CHAPTER THE LOG AND LINE CHAPTER THE LIFE BUOY CHAPTER THE DECK CHAPTER THE PEQUOD MEETS THE RACHEL CHAPTER THE CABIN CHAPTER THE HAT CHAPTER THE PEQUOD MEETS THE DELIGHT CHAPTER " +
  " THE SYMPHONY CHAPTER THE CHASE FIRST DAY CHAPTER THE CHASE SECOND DAY CHAPTER THE CHASE THIRD DAY EPILOGUE ORIGINAL TRANSCRIBER S NOTES THIS TEXT IS A COMBINATION OF ETEXTS ONE FROM THE NOW DEFUNCT ERIS PROJECT AT VIRGINIA TECH AND ONE FROM PROJECT GUTENBERG S ARCHIVES THE PROOFREADERS OF THIS VERSION ARE INDEBTED TO THE UNIVERSITY OF ADELAIDE LIBRARY FOR PRESERVING THE VIRGINIA TECH VERSION THE RESULTING ETEXT WAS COMPARED WITH A PUBLIC DOMAIN HARD COPY VERSION OF THE TEXT ETYMOLOGY SUPPLIED BY A LATE CONSUMPTIVE USHER TO A GRAMMAR SCHOOL THE PALE USHER THREADBARE IN COAT HEART BODY AND BRAIN I SEE HIM NOW HE WAS EVER DUSTING HIS OLD LEXICONS AND GRAMMARS WITH A QUEER HANDKERCHIEF MOCKINGLY EMBELLISHED WITH ALL THE GAY FLAGS OF ALL THE KNOWN NATIONS OF THE WORLD HE LOVED TO DUST HIS OLD GRAMMARS IT SOMEHOW MILDLY REMINDED HIM OF HIS MORTALITY WHILE YOU TAKE IN HAND TO SCHOOL OTHERS AND TO TEACH THEM BY WHAT NAME A WHALE FISH IS TO BE CALLED IN OUR TONGUE LEAVING OUT THROUGH IGNORANCE " +
  " TH THE ADVENTURES OF TOM SAWYER BY MARK TWAIN SAMUEL LANGHORNE CLEMENS CONTENTS CHAPTER I Y O U U TOM AUNT POLLY DECIDES UPON HER DUTY TOM PRACTICES MUSIC THE CHALLENGE A PRIVATE ENTRANCE CHAPTER II STRONG TEMPTATIONS STRATEGIC MOVEMENTS THE INNOCENTS BEGUILED CHAPTER III TOM AS A GENERAL TRIUMPH AND REWARD DISMAL FELICITY COMMISSION AND OMISSION CHAPTER IV MENTAL ACROBATICS ATTENDING SUNDAY SCHOOL THE SUPERINTENDENT SHOWING OFF TOM LIONIZED CHAPTER V A USEFUL MINISTER IN CHURCH THE CLIMAX CHAPTER VI SELF EXAMINATION DENTISTRY THE MIDNIGHT CHARM WITCHES AND DEVILS CAUTIOUS APPROACHES HAPPY HOURS CHAPTER VII A TREATY ENTERED INTO EARLY LESSONS A MISTAKE MADE CHAPTER VIII TOM DECIDES ON HIS COURSE OLD SCENES RE ENACTED CHAPTER IX A SOLEMN SITUATION GRAVE SUBJECTS INTRODUCED INJUN JOE EXPLAINS CHAPTER X THE SOLEMN OATH TERROR BRINGS REPENTANCE MENTAL PUNISHMENT CHAPTER XI MUFF POTTER COMES HIMSELF TOM S CONSCIENCE AT WORK CHAPTER XII TOM SHOWS HIS GENEROSITY AUNT POLLY WEAKENS CHAPTER XI " +
  "II THE YOUNG PIRATES GOING TO THE RENDEZVOUS THE CAMP FIRE TALK CHAPTER XIV CAMP LIFE A SENSATION TOM STEALS AWAY FROM CAMP CHAPTER XV TOM RECONNOITERS LEARNS THE SITUATION REPORTS AT CAMP CHAPTER XVI A DAY S AMUSEMENTS TOM REVEALS A SECRET THE PIRATES TAKE A LESSON A NIGHT SURPRISE AN INDIAN WAR CHAPTER XVII MEMORIES OF THE LOST HEROES THE POINT IN TOM S SECRET CHAPTER XVIII TOM S FEELINGS INVESTIGATED WONDERFUL DREAM BECKY THATCHER OVERSHADOWED TOM BECOMES JEALOUS BLACK REVENGE CHAPTER XIX TOM TELLS THE TRUTH CHAPTER XX BECKY IN A DILEMMA TOM S NOBILITY ASSERTS ITSELF CHAPTER XXI YOUTHFUL ELOQUENCE COMPOSITIONS BY THE YOUNG LADIES A LENGTHY VISION THE BOY S VENGEANCE SATISFIED CHAPTER XXII TOM S CONFIDENCE BETRAYED EXPECTS SIGNAL PUNISHMENT CHAPTER XXIII OLD MUFF S FRIENDS MUFF POTTER IN COURT MUFF POTTER SAVED CHAPTER XXIV TOM AS THE VILLAGE HERO DAYS OF SPLENDOR AND NIGHTS OF HORROR PURSUIT OF INJUN JOE CHAPTER XXV ABOUT KINGS AND DIAMONDS SEARCH FOR THE TREASURE DEAD PEOPLE AND GH " +
  "OSTS CHAPTER XXVI THE HAUNTED HOUSE SLEEPY GHOSTS A BOX OF GOLD BITTER LUCK CHAPTER XXVII DOUBTS TO BE SETTLED THE YOUNG DETECTIVES CHAPTER XXVIII AN ATTEMPT AT NO TWO HUCK MOUNTS GUARD CHAPTER XXIX THE PIC NIC HUCK ON INJUN JOE S TRACK THE REVENGE JOB AID FOR THE WIDOW CHAPTER XXX THE WELSHMAN REPORTS HUCK UNDER FIRE THE STORY CIRCULATED A NEW SENSATION HOPE GIVING WAY TO DESPAIR CHAPTER XXXI AN EXPLORING EXPEDITION TROUBLE COMMENCES LOST IN THE CAVE TOTAL DARKNESS FOUND BUT NOT SAVED CHAPTER XXXII TOM TELLS THE STORY OF THEIR ESCAPE TOM S ENEMY IN SAFE QUARTERS CHAPTER XXXIII THE FATE OF INJUN JOE HUCK AND TOM COMPARE NOTES AN EXPEDITION TO THE CAVE PROTECTION AGAINST GHOSTS AN AWFUL SNUG PLACE A RECEPTION AT THE WIDOW DOUGLAS S CHAPTER XXXIV SPRINGING A SECRET MR JONES SURPRISE A FAILURE CHAPTER XXXV A NEW ORDER OF THINGS POOR HUCK NEW ADVENTURES PLANNED ILLUSTRATIONS TOM SAWYER TOM AT HOME AUNT POLLY BEGUILED A GOOD OPPORTUNITY WHO S AFRAID LATE HOME JIM TENDIN TO BUSINESS AIN T TH " +
  "AT WORK CAT AND TOYS AMUSEMENT BECKY THATCHER PAYING OFF AFTER THE BATTLE SHOWING OFF NOT AMISS MARY TOM CONTEMPLATING DAMPENED ARDOR YOUTH BOYHOOD USING THE BARLOW THE CHURCH NECESSITIES TOM AS A SUNDAY SCHOOL HERO THE PRIZE AT CHURCH THE MODEL BOY THE CHURCH CHOIR A SIDE SHOW RESULT OF PLAYING IN CHURCH THE PINCH BUG SID DENTISTRY HUCKLEBERRY FINN MOTHER HOPKINS RESULT OF TOM S TRUTHFULNESS TOM AS AN ARTIST INTERRUPTED COURTSHIP THE MASTER VAIN PLEADING TAIL PIECE THE GRAVE IN THE WOODS TOM MEDITATES ROBIN HOOD AND HIS FOE DEATH OF ROBIN HOOD MIDNIGHT TOM S MODE OF EGRESS TOM S EFFORT AT PRAYER MUFF POTTER OUTWITTED THE GRAVEYARD FOREWARNINGS DISTURBING MUFF S SLEEP TOM S TALK WITH HIS AUNT MUFF POTTER A SUSPICIOUS INCIDENT INJUN JOE S TWO VICTIMS IN THE COILS PETER AUNT POLLY SEEKS INFORMATION A GENERAL GOOD TIME DEMORALIZED JOE HARPER ON BOARD THEIR FIRST PRIZE THE PIRATES ASHORE WILD LIFE THE PIRATE S BATH THE PLEASANT STROLL THE SEARCH FOR THE DROWNED THE MYSTERIOUS WRITING RIVER " +
  " VIEW WHAT TOM SAW TOM SWIMS THE RIVER TAKING LESSONS THE PIRATES EGG MARKET TOM LOOKING FOR JOE S KNIFE THE THUNDER STORM TERRIBLE SLAUGHTER THE MOURNER TOM S PROUDEST MOMENT AMY LAWRENCE TOM TRIES TO REMEMBER THE HERO A FLIRTATION BECKY RETALIATES A SUDDEN FROST COUNTER IRRITATION AUNT POLLY TOM JUSTIFIED THE DISCOVERY CAUGHT IN THE ACT TOM ASTONISHES THE SCHOOL LITERATURE TOM DECLAIMS EXAMINATION EVENING ON EXHIBITION PRIZE AUTHORS THE MASTER S DILEMMA THE SCHOOL HOUSE THE CADET HAPPY FOR TWO DAY FRANKENSTEIN OR THE MODERN PROMETHEUS BY MARY WOLLSTONECRAFT GODWIN SHELLEY CONTENTS LETTER LETTER LETTER LETTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER CHAPTER LETTER TO MRS SAVILLE ENGLAND ST PETERSBURGH DEC TH YOU WILL REJOICE TO HEAR THAT NO DISASTER HAS ACCOMPANIED THE COMMENCEMENT OF AN ENTERPRISE WHICH YOU HAVE REGARDED WITH SUCH EVIL FOREBOD " +
  "INGS I ARRIVED HERE YESTERDAY AND MY FIRST TASK IS TO ASSURE MY DEAR SISTER OF MY WELFARE AND INCREASING CONFIDENCE IN THE SUCCESS OF MY UNDERTAKING I AM ALREADY FAR NORTH OF LONDON AND AS I WALK IN THE STREETS OF PETERSBURGH I FEEL A COLD NORTHERN BREEZE PLAY UPON MY CHEEKS WHICH BRACES MY NERVES AND FILLS ME WITH DELIGHT DO YOU UNDERSTAND THIS FEELING THIS BREEZE WHICH HAS TRAVELLED FROM THE REGIONS TOWARDS WHICH I AM ADVANCING GIVES ME A FORETASTE OF THOSE ICY CLIMES INSPIRITED BY THIS WIND OF PROMISE MY DAYDREAMS BECOME MORE FERVENT AND VIVID I TRY IN VAIN TO BE PERSUADED THAT THE POLE IS THE SEAT OF FROST AND DESOLATION IT EVER PRESENTS ITSELF TO MY IMAGINATION AS THE REGION OF BEAUTY AND DELIGHT THERE MARGARET THE SUN IS FOR EVER VISIBLE ITS BROAD DISK JUST SKIRTING THE HORIZON AND DIFFUSING A PERPETUAL SPLENDOUR THERE FOR WITH YOUR LEAVE MY SISTER I WILL PUT SOME TRUST IN PRECEDING NAVIGATORS THERE SNOW AND FROST ARE BANISHED AND SAILING OVER A CALM SEA WE MAY BE WAFTED TO A LAN " +
  "D SURPASSING IN WONDERS AND IN BEAUTY EVERY REGION HITHERTO DISCOVERED ON THE HABITABLE GLOBE ITS PRODUCTIONS AND FEATURES MAY BE WITHOUT EXAMPLE AS THE PHENOMENA OF THE HEAVENLY BODIES UNDOUBTEDLY ARE IN THOSE UNDISCOVERED SOLITUDES WHAT MAY NOT BE EXPECTED IN A COUNTRY OF ETERNAL LIGHT I MAY THERE DISCOVER THE WONDROUS POWER WHICH ATTRACTS THE NEEDLE AND MAY REGULATE A THOUSAND CELESTIAL OBSERVATIONS THAT REQUIRE ONLY THIS VOYAGE TO RENDER THEIR SEEMING ECCENTRICITIES CONSISTENT FOR EVER I SHALL SATIATE MY ARDENT CURIOSITY WITH THE SIGHT OF A PART OF THE WORLD NEVER BEFORE VISITED AND MAY TREAD A LAND NEVER BEFORE IMPRINTED BY THE FOOT OF MAN THESE ARE MY ENTICEMENTS AND THEY ARE SUFFICIENT TO CONQUER ALL FEAR OF DANGER OR DEATH AND TO INDUCE ME TO COMMENCE THIS LABORIOUS VOYAGE WITH THE JOY A CHILD FEELS WHEN HE EMBARKS IN A LITTLE BOAT WITH HIS HOLIDAY MATES ON AN EXPEDITION OF DISCOVERY UP HIS NATIVE RIVER BUT SUPPOSING ALL THESE CONJECTURES TO BE FALSE YOU CANNOT CONTEST THE INES " +
  "TIMABLE BENEFIT WHICH I SHALL CONFER ON ALL MANKIND TO THE LAST GENERATION BY DISCOVERING A PASSAGE NEAR THE POLE TO THOSE COUNTRIES TO REACH WHICH AT PRESENT SO MANY MONTHS ARE REQUISITE OR BY ASCERTAINING THE SECRET OF THE MAGNET WHICH IF AT ALL POSSIBLE CAN ONLY BE EFFECTED BY AN UNDERTAKING SUCH AS MINE THESE REFLECTIONS HAVE DISPELLED THE AGITATION WITH WHICH I BEGAN MY LETTER AND I FEEL MY HEART GLOW WITH AN ENTHUSIASM WHICH ELEVATES ME TO HEAVEN FOR NOTHING CONTRIBUTES SO MUCH TO TRANQUILLISE THE MIND AS A STEADY PURPOSE A POINT ON WHICH THE SOUL MAY FIX ITS INTELLECTUAL EYE THIS EXPEDITION HAS BEEN THE FAVOURITE DREAM OF MY EARLY YEARS I HAVE READ WITH ARDOUR THE ACCOUNTS OF THE VARIOUS VOYAGES WHICH HAVE BEEN MADE IN THE PROSPECT OF ARRIVING AT THE NORTH PACIFIC OCEAN THROUGH THE SEAS WHICH SURROUND THE POLE YOU MAY REMEMBER THAT A HISTORY OF ALL THE VOYAGES MADE FOR PURPOSES OF DISCOVERY COMPOSED THE WHOLE OF OUR GOOD UNCLE THOMAS LIBRARY MY EDUCATION WAS NEGLECTED YET I WAS  " +
  "PASSIONATELY FOND OF READING THESE VOLUMES WERE MY STUDY DAY AND NIGHT AND MY FAMILIARITY WITH THEM INCREASED THAT REGRET WHICH I HAD FELT AS A CHILD ON LEARNING THAT MY FATHER S DYING INJUNCTION HAD FORBIDDEN MY UNCLE TO ALLOW ME TO EMBARK IN A SEAFARING LIFE THESE VISIONS FADED WHEN I PERUSED FOR THE FIRST TIME THOSE POETS WHOSE EFFUSIONS ENTRANCED MY SOUL AND LIFTED IT TO HEAVEN I ALSO BECAME A POET AND FOR ONE YEAR LIVED IN A PARADISE OF MY OWN CREATION I IMAGINED THAT I ALSO MIGHT OBTAIN A NICHE IN THE TEMPLE WHERE THE NAMES OF HOMER AND SHAKESPEARE ARE CONSECRATED YOU ARE WELL ACQUAINTED WITH MY FAILURE AND HOW HEAVILY I BORE THE DISAPPOINTMENT BUT JUST AT THAT TIME I INHERITED THE FORTUNE OF MY COUSIN AND MY THOUGHTS WERE TURNED INTO THE CHANNEL OF THEIR EARLIER BENT SIX YEARS HAVE PASSED SINCE I RESOLVED ON MY PRESENT UNDERTAKING I CAN EVEN NOW REMEMBER THE HOUR FROM WHICH I DEDICATED MYSELF TO THIS GREAT ENTERPRISE I COMMENCED BY INURING MY BODY TO HARDSHIP I ACCOMPANIED THE W " +
  "HALE I ONE MORNING WHEN GREGOR SAMSA WOKE FROM TROUBLED DREAMS HE FOUND HIMSELF TRANSFORMED IN HIS BED INTO A HORRIBLE VERMIN HE LAY ON HIS ARMOUR LIKE BACK AND IF HE LIFTED HIS HEAD A LITTLE HE COULD SEE HIS BROWN BELLY SLIGHTLY DOMED AND DIVIDED BY ARCHES INTO STIFF SECTIONS THE BEDDING WAS HARDLY ABLE TO COVER IT AND SEEMED READY TO SLIDE OFF ANY MOMENT HIS MANY LEGS PITIFULLY THIN COMPARED WITH THE SIZE OF THE REST OF HIM WAVED ABOUT HELPLESSLY AS HE LOOKED WHAT S HAPPENED TO ME HE THOUGHT IT WASN T A DREAM HIS ROOM A PROPER HUMAN ROOM ALTHOUGH A LITTLE TOO SMALL LAY PEACEFULLY BETWEEN ITS FOUR FAMILIAR WALLS A COLLECTION OF TEXTILE SAMPLES LAY SPREAD OUT ON THE TABLE SAMSA WAS A TRAVELLING SALESMAN AND ABOVE IT THERE HUNG A PICTURE THAT HE HAD RECENTLY CUT OUT OF AN ILLUSTRATED MAGAZINE AND HOUSED IN A NICE GILDED FRAME IT SHOWED A LADY FITTED OUT WITH A FUR HAT AND FUR BOA WHO SAT UPRIGHT RAISING A HEAVY FUR MUFF THAT COVERED THE WHOLE OF HER LOWER ARM TOWARDS THE VIEWER GREGOR T " +
  "HEN TURNED TO LOOK OUT THE WINDOW AT THE DULL WEATHER DROPS OF RAIN COULD BE HEARD HITTING THE PANE WHICH MADE HIM FEEL QUITE SAD HOW ABOUT IF I SLEEP A LITTLE BIT LONGER AND FORGET ALL THIS NONSENSE HE THOUGHT BUT THAT WAS SOMETHING HE WAS UNABLE TO DO BECAUSE HE WAS USED TO SLEEPING ON HIS RIGHT AND IN HIS PRESENT STATE COULDN T GET INTO THAT POSITION HOWEVER HARD HE THREW HIMSELF ONTO HIS RIGHT HE ALWAYS ROLLED BACK TO WHERE HE WAS HE MUST HAVE TRIED IT A HUNDRED TIMES SHUT HIS EYES SO THAT HE WOULDN T HAVE TO LOOK AT THE FLOUNDERING LEGS AND ONLY STOPPED WHEN HE BEGAN TO FEEL A MILD DULL PAIN THERE THAT HE HAD NEVER FELT BEFORE OH GOD HE THOUGHT WHAT A STRENUOUS CAREER IT IS THAT I VE CHOSEN TRAVELLING DAY IN AND DAY OUT DOING BUSINESS LIKE THIS TAKES MUCH MORE EFFORT THAN DOING YOUR OWN BUSINESS AT HOME AND ON TOP OF THAT THERE S THE CURSE OF TRAVELLING WORRIES ABOUT MAKING TRAIN CONNECTIONS BAD AND IRREGULAR FOOD CONTACT WITH DIFFERENT PEOPLE ALL THE TIME SO THAT YOU CAN NEVER GE " +
  "T TO KNOW ANYONE OR BECOME FRIENDLY WITH THEM IT CAN ALL GO TO HELL HE FELT A SLIGHT ITCH UP ON HIS BELLY PUSHED HIMSELF SLOWLY UP ON HIS BACK TOWARDS THE HEADBOARD SO THAT HE COULD LIFT HIS HEAD BETTER FOUND WHERE THE ITCH WAS AND SAW THAT IT WAS COVERED WITH LOTS OF LITTLE WHITE SPOTS WHICH HE DIDN T KNOW WHAT TO MAKE OF AND WHEN HE TRIED TO FEEL THE PLACE WITH ONE OF HIS LEGS HE DREW IT QUICKLY BACK BECAUSE AS SOON AS HE TOUCHED IT HE WAS OVERCOME BY A COLD SHUDDER HE SLID BACK INTO HIS FORMER POSITION GETTING UP EARLY ALL THE TIME HE THOUGHT IT MAKES YOU STUPID YOU VE GOT TO GET ENOUGH SLEEP OTHER TRAVELLING SALESMEN LIVE A LIFE OF LUXURY FOR INSTANCE WHENEVER I GO BACK TO THE GUEST HOUSE DURING THE MORNING TO COPY OUT THE CONTRACT THESE GENTLEMEN ARE ALWAYS STILL SITTING THERE EATING THEIR BREAKFASTS I OUGHT TO JUST TRY THAT WITH MY BOSS I D GET KICKED OUT ON THE SPOT BUT WHO KNOWS MAYBE THAT WOULD BE THE BEST THING FOR ME IF I DIDN T HAVE MY PARENTS TO THINK ABOUT I D HAVE GIVEN  " +
  "IN MY NOTICE A LONG TIME AGO I D HAVE GONE UP TO THE BOSS AND TOLD HIM JUST WHAT I THINK TELL HIM EVERYTHING I WOULD LET HIM KNOW JUST WHAT I FEEL HE D FALL RIGHT OFF HIS DESK AND IT S A FUNNY SORT OF BUSINESS TO BE SITTING UP THERE AT YOUR DESK TALKING DOWN AT YOUR SUBORDINATES FROM UP THERE ESPECIALLY WHEN YOU HAVE TO GO RIGHT UP CLOSE BECAUSE THE BOSS IS HARD OF HEARING WELL THERE S STILL SOME HOPE ONCE I VE GOT THE MONEY TOGETHER TO PAY OFF MY PARENTS DEBT TO HIM ANOTHER FIVE OR SIX YEARS I SUPPOSE THAT S DEFINITELY WHAT I LL DO THAT S WHEN I LL MAKE THE BIG CHANGE FIRST OF ALL THOUGH I VE GOT TO GET UP MY TRAIN LEAVES AT FIVE AND HE LOOKED OVER AT THE ALARM CLOCK TICKING ON THE CHEST OF DRAWERS GOD IN HEAVEN HE THOUGHT IT WAS HALF PAST SIX AND THE HANDS WERE QUIETLY MOVING FORWARDS IT WAS EVEN LATER THAN HALF PAST MORE LIKE QUARTER TO SEVEN HAD THE ALARM CLOCK NOT RUNG HE COULD SEE FROM THE BED THAT IT HAD BEEN SET FOR FOUR O CLOCK AS IT SHOULD HAVE BEEN IT CERTAINLY MUST HAVE RUN " +
  "G YES BUT WAS IT POSSIBLE TO QUIETLY SLEEP THROUGH THAT FURNITURE RATTLING NOISE TRUE HE HAD NOT SLEPT PEACEFULLY BUT PROBABLY ALL THE MORE DEEPLY BECAUSE OF THAT WHAT SHOULD HE DO NOW THE NEXT TRAIN WENT AT SEVEN IF HE WERE TO CATCH THAT HE WOULD HAVE TO RUSH LIKE MAD AND THE COLLECTION OF SAMPLES WAS STILL NOT PACKED AND HE DID NOT AT ALL FEEL PARTICULARLY FRESH AND LIVELY AND EVEN IF HE DID CATCH THE TRAIN HE WOULD NOT AVOID HIS BOSS S ANGER AS THE OFFICE ASSISTANT WOULD HAVE BEEN THERE TO SEE THE ADVENTURES OF HUCKLEBERRY FINN TOM SAWYER S COMRADE BY MARK TWAIN CONTENTS CHAPTER I CIVILIZING HUCK MISS WATSON TOM SAWYER WAITS CHAPTER II THE BOYS ESCAPE JIM TORN SAWYER S GANG DEEP LAID PLANS CHAPTER III A GOOD GOING OVER GRACE TRIUMPHANT ONE OF TOM SAWYERS S LIES CHAPTER IV HUCK AND THE JUDGE SUPERSTITION CHAPTER V HUCK S FATHER THE FOND PARENT REFORM CHAPTER VI HE WENT FOR JUDGE THATCHER HUCK DECIDED TO LEAVE POLITICAL ECONOMY THRASHING AROUND CHAPTER VII LAYING FOR HIM LOCKED IN THE " +
  " CABIN SINKING THE BODY RESTING CHAPTER VIII SLEEPING IN THE WOODS RAISING THE DEAD EXPLORING THE ISLAND FINDING JIM JIM S ESCAPE SIGNS BALUM CHAPTER IX THE CAVE THE FLOATING HOUSE CHAPTER X THE FIND OLD HANK BUNKER IN DISGUISE CHAPTER XI HUCK AND THE WOMAN THE SEARCH PREVARICATION GOING TO GOSHEN CHAPTER XII SLOW NAVIGATION BORROWING THINGS BOARDING THE WRECK THE PLOTTERS HUNTING FOR THE BOAT CHAPTER XIII ESCAPING FROM THE WRECK THE WATCHMAN SINKING CHAPTER XIV A GENERAL GOOD TIME THE HAREM FRENCH CHAPTER XV HUCK LOSES THE RAFT IN THE FOG HUCK FINDS THE RAFT TRASH CHAPTER XVI EXPECTATION A WHITE LIE FLOATING CURRENCY RUNNING BY CAIRO SWIMMING ASHORE CHAPTER XVII AN EVENING CALL THE FARM IN ARKANSAW INTERIOR DECORATIONS STEPHEN DOWLING BOTS POETICAL EFFUSIONS CHAPTER XVIII COL GRANGERFORD ARISTOCRACY FEUDS THE TESTAMENT RECOVERING THE RAFT THE WOOD PILE PORK AND CABBAGE CHAPTER XIX TYING UP DAY TIMES AN ASTRONOMICAL THEORY RUNNING A TEMPERANCE REVIVAL THE DUKE OF BRIDGEWATER THE TROUBL " +
  "ES OF ROYALTY CHAPTER XX HUCK EXPLAINS LAYING OUT A CAMPAIGN WORKING THE CAMP MEETING A PIRATE AT THE CAMP MEETING THE DUKE AS A PRINTER CHAPTER XXI SWORD EXERCISE HAMLET S SOLILOQUY THEY LOAFED AROUND TOWN A LAZY TOWN OLD BOGGS DEAD CHAPTER XXII SHERBURN ATTENDING THE CIRCUS INTOXICATION IN THE RING THE THRILLING TRAGEDY CHAPTER XXIII SOLD ROYAL COMPARISONS JIM GETS HOME SICK CHAPTER XXIV JIM IN ROYAL ROBES THEY TAKE A PASSENGER GETTING INFORMATION FAMILY GRIEF CHAPTER XXV IS IT THEM SINGING THE DOXOLOGER AWFUL SQUARE FUNERAL ORGIES A BAD INVESTMENT CHAPTER XXVI A PIOUS KING THE KING S CLERGY SHE ASKED HIS PARDON HIDING IN THE ROOM HUCK TAKES THE MONEY CHAPTER XXVII THE FUNERAL SATISFYING CURIOSITY SUSPICIOUS OF HUCK QUICK SALES AND SMALL CHAPTER XXVIII THE TRIP TO ENGLAND THE BRUTE MARY JANE DECIDES TO LEAVE HUCK PARTING WITH MARY JANE MUMPS THE OPPOSITION LINE CHAPTER XXIX CONTESTED RELATIONSHIP THE KING EXPLAINS THE LOSS A QUESTION OF HANDWRITING DIGGING UP THE CORPSE HUCK ESCAPES  " +
  "CHAPTER XXX THE KING WENT FOR HIM A ROYAL ROW POWERFUL MELLOW CHAPTER XXXI OMINOUS PLANS NEWS FROM JIM OLD RECOLLECTIONS A SHEEP STORY VALUABLE INFORMATION CHAPTER XXXII STILL AND SUNDAY LIKE MISTAKEN IDENTITY UP A STUMP IN A DILEMMA CHAPTER XXXIII A NIGGER STEALER SOUTHERN HOSPITALITY A PRETTY LONG BLESSING TAR AND FEATHERS CHAPTER XXXIV THE HUT BY THE ASH HOPPER OUTRAGEOUS CLIMBING THE LIGHTNING ROD TROUBLED WITH WITCHES CHAPTER XXXV ESCAPING PROPERLY DARK SCHEMES DISCRIMINATION IN STEALING A DEEP HOLE CHAPTER XXXVI THE LIGHTNING ROD HIS LEVEL BEST A BEQUEST TO POSTERITY A HIGH FIGURE CHAPTER XXXVII THE LAST SHIRT MOONING AROUND SAILING ORDERS THE WITCH PIE CHAPTER XXXVIII THE COAT OF ARMS A SKILLED SUPERINTENDENT UNPLEASANT GLORY A TEARFUL SUBJECT CHAPTER XXXIX RATS LIVELY BED FELLOWS THE STRAW DUMMY CHAPTER XL FISHING THE VIGILANCE COMMITTEE A LIVELY RUN JIM ADVISES A DOCTOR CHAPTER XLI THE DOCTOR UNCLE SILAS SISTER HOTCHKISS AUNT SALLY IN TROUBLE CHAPTER XLII TOM SAWYER WOUNDED TH " +
  "E DOCTOR S STORY TOM CONFESSES AUNT POLLY ARRIVES HAND OUT THEM LETTERS CHAPTER THE LAST OUT OF BONDAGE PAYING THE CAPTIVE YOURS TRULY HUCK FINN ILLUSTRATIONS THE WIDOWS MOSES AND THE BULRUSHERS MISS WATSON HUCK STEALING AWAY THEY TIP TOED ALONG JIM TOM SAWYER S BAND OF ROBBERS HUCK CREEPS INTO HIS WINDOW MISS WATSON S LECTURE THE ROBBERS DISPERSED RUBBING THE LAMP JUDGE THATCHER SURPRISED JIM LISTENING PAP HUCK AND HIS FATHER REFORMING THE DRUNKARD FALLING FROM GRACE GETTING OUT OF THE WAY SOLID COMFORT THINKING IT OVER RAISING A HOWL GIT UP THE SHANTY SHOOTING THE PIG TAKING A REST IN THE WOODS WATCHING THE BOAT DISCOVERING THE CAMP FIRE JIM AND THE GHOST MISTO BRADISH S NIGGER EXPLORING THE CAVE IN THE CAVE JIM SEES A DEAD MAN THEY FOUND EIGHT DOLLARS JIM AND THE SNAKE OLD HANK BUNKER A FAIR FIT COME IN HIM AND ANOTHER MAN SHE PUTS UP A SNACK HUMP YOURSELF ON THE RAFT HE SOMETIMES LIFTED A CHICKEN PLEASE DON T BILL IT AIN T GOOD MORALS OH LORDY LORDY IN A FIX HELLO WHAT S UP THE WRE " +
  "CK WE "
);

// N-gram 频率表：quadgram 主信号 + trigram/bigram 回退（解决接近最优时四元组命中稀疏、梯度消失问题）
const _QUAD = new Map();
const _TRI = new Map();
const _BI = new Map();
// 数字键镜像表（26 进制整数编码，值直接存 log2 分）：单表爬山热点路径专用，免字符串分配
const _QUADN = new Map();
const _TRIN = new Map();
const _BIN = new Map();
{
  const c = cleanLetters(CORPUS);
  for (let i = 0; i + 4 <= c.length; i++) {
    const q = c.slice(i, i + 4);
    _QUAD.set(q, (_QUAD.get(q) || 0) + 1);
  }
  for (let i = 0; i + 3 <= c.length; i++) {
    const t = c.slice(i, i + 3);
    _TRI.set(t, (_TRI.get(t) || 0) + 1);
  }
  for (let i = 0; i + 2 <= c.length; i++) {
    const b = c.slice(i, i + 2);
    _BI.set(b, (_BI.get(b) || 0) + 1);
  }
  const d = new Uint8Array(c.length);
  for (let i = 0; i < c.length; i++) d[i] = c.charCodeAt(i) - 65;
  const L2 = 1 / Math.log(2);
  const countN = new Map();
  for (let i = 0; i + 4 <= d.length; i++) {
    const v = ((d[i] * 26 + d[i + 1]) * 26 + d[i + 2]) * 26 + d[i + 3];
    countN.set(v, (countN.get(v) || 0) + 1);
  }
  for (const [v, n] of countN) _QUADN.set(v, Math.log(n + 1) * L2);
  const countT = new Map();
  for (let i = 0; i + 3 <= d.length; i++) {
    const v = (d[i] * 26 + d[i + 1]) * 26 + d[i + 2];
    countT.set(v, (countT.get(v) || 0) + 1);
  }
  for (const [v, n] of countT) _TRIN.set(v, Math.log(n + 1) * L2);
  const countB = new Map();
  for (let i = 0; i + 2 <= d.length; i++) {
    const v = d[i] * 26 + d[i + 1];
    countB.set(v, (countB.get(v) || 0) + 1);
  }
  for (const [v, n] of countB) _BIN.set(v, Math.log(n + 1) * L2);
}
const _LOG2 = Math.log(2);
// 适应度 = quadgram(主) + 0.3*trigram(辅助) + 0.1*bigram(兜底)
// 三层联合使真值文本 fitness 显著高于局部最优，且近最优区仍有密集梯度
function quadFitness(text) {
  const c = cleanLetters(text);
  let score = 0;
  for (let i = 0; i + 4 <= c.length; i++) {
    const q = c.slice(i, i + 4);
    score += Math.log((_QUAD.get(q) || 0) + 1) / _LOG2;
  }
  for (let i = 0; i + 3 <= c.length; i++) {
    const t = c.slice(i, i + 3);
    score += 0.3 * Math.log((_TRI.get(t) || 0) + 1) / _LOG2;
  }
  for (let i = 0; i + 2 <= c.length; i++) {
    const b = c.slice(i, i + 2);
    score += 0.1 * Math.log((_BI.get(b) || 0) + 1) / _LOG2;
  }
  return score;
}

// 用 25 字母方阵解密（与 classic.js playfairDecode 规则一致：完整方阵即 keyword）
function playfairDecryptSquare(ct, square) {
  return playfairDecode(ct, square);
}

function playfairHillClimb(ct, { iterations = 8000, seed = 1, startSquare = null } = {}) {
  const rng = mulberry32(seed);
  let square = (startSquare || AZ_NO_J).split("");
  let bestPlain = playfairDecryptSquare(ct, square.join(""));
  let bestFit = quadFitness(bestPlain);
  let bestSquare = square.slice();
  let curFit = bestFit;
  let curSquare = square.slice();

  for (let it = 0; it < iterations; it++) {
 // 温度：保守策略——温标 ~4→0.3，早期仅允许小幅探索，避免丢失 warm-start 结构；后期纯爬山
    const temp = 0.3 + 3.7 * Math.pow(1 - it / iterations, 1.5);
 // 重入：每 300 次迭代把 cur 拉回 best，防止 SA 长程游走错过最优
    if (it > 0 && it % 300 === 0) {
      curSquare = bestSquare.slice();
      curFit = bestFit;
    }
    const cand = curSquare.slice();
    const move = Math.floor(rng() * 3);
    if (move === 0) {
      const a = Math.floor(rng() * 25), b = Math.floor(rng() * 25);
      [cand[a], cand[b]] = [cand[b], cand[a]];
    } else if (move === 1) {
      const r1 = Math.floor(rng() * 5), r2 = Math.floor(rng() * 5);
      for (let c = 0; c < 5; c++) { const t = cand[r1 * 5 + c]; cand[r1 * 5 + c] = cand[r2 * 5 + c]; cand[r2 * 5 + c] = t; }
    } else {
      const c1 = Math.floor(rng() * 5), c2 = Math.floor(rng() * 5);
      for (let r = 0; r < 5; r++) { const t = cand[r * 5 + c1]; cand[r * 5 + c1] = cand[r * 5 + c2]; cand[r * 5 + c2] = t; }
    }
    const cPlain = playfairDecryptSquare(ct, cand.join(""));
    const cFit = quadFitness(cPlain);
    const dFit = cFit - curFit;
    if (dFit >= 0 || rng() < Math.exp(dFit / temp)) {
      curSquare = cand;
      curFit = cFit;
      if (cFit > bestFit) {
        bestFit = cFit;
        bestSquare = cand.slice();
        bestPlain = cPlain;
      }
    }
  }
  return { square: bestSquare.join(""), plain: bestPlain, fitness: bestFit };
}

// ============================================================
// 通用单表替换爬山内核（subCipherSolver 委托此内核；与 playfairHillClimb 共用
// quadFitness 三层适应度与 mulberry32，对象是 26 字母全置换，支持已知映射锁定。
// 搜索策略用 first-improvement 穷举对序 + 外层多重启——swap 邻域上随机抽对的
// 贪心/SA 实测都会卡「两字母错」局部最优，穷举对序才是文献标准打法）
// ============================================================
function subApplyKey(ct, key) {
 // ct 已是纯大写 A-Z：直接按位查映射，避免逐字符正则（爬山热点路径）
  let out = "";
  for (let i = 0; i < ct.length; i++) out += key[ct.charCodeAt(i) - 65];
  return out;
}

// locked: Map<密文序号 0-25, 明文序号 0-25>，锁定对不参与交换（人工已知线索）
function substitutionHillClimb(ct, { iterations = 10000, seed = 1, startKey = null, locked = null } = {}) {
  const rng = mulberry32(seed);
  const start = Array.isArray(startKey) ? startKey.slice() : (startKey || AZ).split("");
  const isLocked = new Array(26).fill(false);
 // 防御式落位：无论起点给什么，锁定位强制为已知明文（锁定位不参与交换，起点错了就永远错）
  if (locked) for (const [c, pl] of locked) { start[c] = AZ[pl]; isLocked[c] = true; }

 // 可交换的密文字母对（排除锁定项，避免白耗评估预算）
  const free = [];
  for (let i = 0; i < 26; i++) if (!isLocked[i]) free.push(i);
  if (free.length < 2) {
    const plain0 = subApplyKey(ct, start);
    return { key: start.join(""), plain: plain0, fitness: quadFitness(plain0) };
  }
 // 密文转数字流：热点路径在数字空间完成映射查表 + 滑窗打分，零字符串分配
  const ctD = new Uint8Array(ct.length);
  for (let i = 0; i < ct.length; i++) ctD[i] = ct.charCodeAt(i) - 65;
 // 全分 = quad(1) + tri(0.3) + bi(0.1)，与 quadFitness 同语料同权重（缺失记 0 = log2(1)）
  const fitOf = (k) => {
    let score = 0;
    let a = 0, b = 0, c = 0;
    for (let i = 0; i < ctD.length; i++) {
      const p = k[ctD[i]];
      if (i >= 3) score += _QUADN.get(((a * 26 + b) * 26 + c) * 26 + p) || 0;
      if (i >= 2) score += 0.3 * (_TRIN.get((b * 26 + c) * 26 + p) || 0);
      if (i >= 1) score += 0.1 * (_BIN.get(c * 26 + p) || 0);
      a = b; b = c; c = p;
    }
    return score;
  };
 // 一轮：随机序遍历全部可交换对，first-improvement（改善即落座）；整轮无改善即收敛
  const pairCount = free.length * (free.length - 1) / 2;
  const climb = (k0) => {
    let key = k0.slice();
    let fit = fitOf(key);
    for (;;) {
      const order = [];
      for (let i = 0; i < free.length; i++) for (let j = i + 1; j < free.length; j++) order.push([free[i], free[j]]);
      for (let i = order.length - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); const t = order[i]; order[i] = order[j]; order[j] = t; }
      let improved = false;
      for (const [a, b] of order) {
        const cand = key.slice();
        const t = cand[a]; cand[a] = cand[b]; cand[b] = t;
        const cFit = fitOf(cand);
        if (cFit > fit) { key = cand; fit = cFit; improved = true; }
      }
      if (!improved) return { key, fit };
    }
  };
 // ILS：起点爬到收敛 → 从 best 做 2~4 次随机 swap 扰动再爬，直到评估预算耗尽。
 //实测：真解常只距局部最优两次交换（单次 swap 无改善贪心即死），扰动可跨盆地；
 // 随机抽对的贪心与 SA 都会卡「两字母错」局部最优，穷举对序 + 扰动才是文献标准打法。
  const startD = start.map((ch) => ch.charCodeAt(0) - 65);
  let best = climb(startD);
  let evals = pairCount;
  while (evals < iterations) {
    const cand = best.key.slice();
    const nSw = 2 + Math.floor(rng() * 3);
    for (let s = 0; s < nSw; s++) {
      const a = free[Math.floor(rng() * free.length)];
      const b = free[Math.floor(rng() * free.length)];
      const t = cand[a]; cand[a] = cand[b]; cand[b] = t;
    }
    const r = climb(cand);
    evals += pairCount;
    if (r.fit > best.fit) best = r;
  }
  const keyStr = best.key.map((code) => AZ[code]).join("");
  return { key: keyStr, plain: subApplyKey(ct, keyStr), fitness: best.fit };
}

function playfairCrack(text, p = {}) {
  const ct = cleanLetters(text);
  const iterations = Number(p && p.iterations) || 9000;
  const lines = [];
  lines.push("=== Playfair 爬山破解 ===");
  lines.push(`密文长度：${ct.length}（仅字母）`);
  if (ct.length < 40) {
    lines.push("（密文过短，爬山大概率不收敛，需 ≥60 字符）");
  }
  lines.push("");
  const restarts = ct.length >= 60 ? 3 : 1;
  let best = { square: AZ_NO_J, plain: "", fitness: -Infinity };
  const rng = mulberry32(20240708);
  for (let r = 0; r < restarts; r++) {
    let startSquare = AZ_NO_J;
    if (r > 0) {
      const s = AZ_NO_J.split("");
      for (let i = s.length - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); [s[i], s[j]] = [s[j], s[i]]; }
      startSquare = s.join("");
    }
    const res = playfairHillClimb(ct, { iterations, seed: 1 + r * 1000, startSquare });
    if (res.fitness > best.fitness) best = res;
  }
  lines.push(`恢复方阵（25 字母）：${best.square}`);
  lines.push(`适应度：${best.fitness.toFixed(2)}`);
  lines.push("");
  lines.push("--- 解密结果 ---");
  lines.push(best.plain);
  lines.push("");
  lines.push("提示：爬山为概率算法，长密文收敛更稳；方阵等价排列可能不同但解密一致。");
  return lines.join("\n");
}

// ============================================================
// 注册
// ============================================================
register({
  id: "vigenereAuto",
  cat: "analysis",
  name: "维吉尼亚全自动破解",
  desc: "IC 估密钥长度 + 列卡方恢复密钥 + 自动解密（英语统计）",
  params: [{ key: "maxKeyLen", label: "最大密钥长度", type: "number", default: 20 }],
  run: vigenereAuto,
});

register({
  id: "hillKnownPlain",
  cat: "analysis",
  name: "Hill 已知明文攻击",
  desc: "已知明文+密文还原 Hill 密钥矩阵（C·P⁻¹ mod 26，须可逆）",
  params: [
    { key: "cipher", label: "对应密文", type: "text", default: "" },
    { key: "size", label: "矩阵阶 n", type: "number", default: 2 },
  ],
  run: hillKnownPlain,
});

register({
  id: "playfairCrack",
  cat: "analysis",
  name: "Playfair 爬山破解",
  desc: "模拟退火 + 四元组适应度爬山恢复 Playfair 方阵与明文（长密文更稳）",
  params: [{ key: "iterations", label: "迭代次数", type: "number", default: 9000 }],
  run: playfairCrack,
});

export {
  vigenereAuto, hillKnownPlain, playfairCrack,
  indexCoincidence, guessKeyLength, recoverVigenereKey,
  matMulMod, lettersToColumnMatrix,
  quadFitness, playfairDecryptSquare, playfairHillClimb,
  substitutionHillClimb,
};
